guardian/riff-raff

- riff-raff/app/views/api/form.scala.html
- riff-raff/app/views/auth/form.scala.html
- riff-raff/app/views/continuousDeployment/form.scala.html
- riff-raff/app/views/deploy/form.scala.html
- riff-raff/app/views/hooks/form.scala.html
- riff-raff/app/views/test/form.scala.html
- riff-raff/build.sbt
This works better and gets rid of all those warnings.
> Use http://play-bootstrap3.herokuapp.com/

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- Now the CFN task does creation as well as updates, check for those events
too
- When checking for an update, ensure that the stackname is what we expect
> Improve cloudformation check logic

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
The code already supports various options to configure S3 uploads, but they aren't accessible to the end developer! And I'd really like to use them.
> Support S3 prefix configuration

- riff-raff/app/controllers/Testing.scala
- riff-raff/app/views/test/s3Latencies.scala.html
- riff-raff/conf/routes
Given that I wrote it, I thought I may as well check it in to make future analysis easier.
> Add S3 latency analysis page

- cloudformation/riffraff.template
Includes expiration policy and IAM groups and policies.
Note that I haven't yet tried actually running this.
> Template for RiffRaff S3 buckets

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
StackName which is same for all levels
> For nested stacks, top-level identified by LogicalResourceId

- project/MagentaBuild.scala
- riff-raff/app/deployment/model.scala
- riff-raff/app/views/snippets/recordTable.scala.html
It shows how long completed builds took to complete.
I think this is a metric that people should be looking at and trying to reduce, so I'd like to increase its visibility.
Note: I didn't bother setting up RiffRaff to run locally, so I've no idea if it works. But it compiles!
> Add a "Time taken" column to the history page

- riff-raff/app/deployment/Deployments.scala
Not sure why Riff-Raff keeps falling over - but this is a possibility, so let's ensure that exceptions here are not propagated.
> Catch and log any exceptions thrown by the update method

- magenta-lib/docs/magenta-lib/howto/fix-a-bad-deploy.md
- magenta-lib/docs/magenta-lib/howto/fix-a-failed-deploy.md
We  had a bad deploy on Monday, and it exposed that we weren't really sure of the best way to reset the state of the ASG, seems worth documenting!
@philwills @sihil @tackley @chrisjowen @tudorraul
> Add instructions on fixing a failed deploy

- cloudformation/riffraff.template
This has already been applied, so just an FYI.
> Allow composer account access to buckets

- riff-raff/app/ci/ContinuousDeployment.scala
A future timing out or the like should not cause all CD to stop
> CD deploys shouldn't propagate errors

- cloudformation/riffraff.template
Added gu-membership account access to the riffraff buckets
> Added Membership to Accout access

- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
Fix typo and document required permissions for lambda task. CC @philwills
> update documentation re: permissions

- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
Correctly parses the extension of filenames containing dots.
> Fix extension parsing

- project/MagentaBuild.scala
- project/plugins.sbt
- riff-raff/build.sbt
- riff-raff/conf/deploy.json
- Switches to native packager from assembly 
- Added s3 upload artefact to deploy.json
> Prepare riffraff to deploy to aws

- riff-raff/app/notification/hooks.scala
Utilising the hacking skills of @philwills, this will set the body of webhooks to json if it fits a valid json format. This to allow passing parameters to Circle CI as they require the header to be set to "Content-Type: application/json"
> Send webhook body as json if valid json

- riff-raff/app/ci/ContinuousDeployment.scala
The one part of the continuous deployment chain that was able to  cause it to die completely was if the call to Mongo to get the configs fails.
This happened this morning, hence my desire to do this now.
cc @guardian/deploy-infrastructure
> Retry CD loop if Mongo fails

- riff-raff/app/persistence/mongodb.scala
It doesn't exist in the new database and isn't used.
> Remove references to old 'hooks' collection

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- this PR _should_ fix the deployment of yaml cloudformation templates
- it also adds bit more information in the case the JSON is invalid
It needs to be tested in a CODE environment, so this should be blocked until we have a CODE environment in AWS for riff-raff
cc @cb372
> Fix yaml deployment

- riff-raff/app/ci/ContinuousDeployment.scala
- riff-raff/app/persistence/datastore.scala
- riff-raff/app/persistence/mongodb.scala
- riff-raff/test/ci/ContinuousDeploymentTest.scala
This is yet another attempt to fix CD.
> Move error handling out of observable and retry mongo

- riff-raff/app/ci/ContinuousDeployment.scala
> Don't just get CD config at startup

- riff-raff/app/ci/ContinuousDeployment.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/controllers/ContinuousDeployController.scala
- riff-raff/app/persistence/ContinuousDeploymentConfigRepository.scala
- riff-raff/build.sbt
- riff-raff/test/MigrateCDConfigs.scala
cc @adamnfish @sihil 
One question is whether we should put the table definition in the associated cloudformation template or not. On Ophan we came to the conclusion that it was often more trouble than it's worth, but I'm happy to be convinced otherwise.
> Use DynamoDB for continuous deployment config

- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
Prevents:
> Unhandled exception in task TagCurrentInstancesWithTerminationTag Tag existing instances of the auto-scaling group for termination
> Check for zero size asg.

- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- riff-raff/app/deployment/model.scala
- riff-raff/app/views/deploy/viewDeploy.scala.html
- riff-raff/app/views/snippets/recordTable.scala.html
Also:
- replaces host with stack in recent deploys table
- adds stack to ASG doubling log message
> Add stack name to deployment report heading 

- riff-raff/app/conf/context.scala
> Use deployTools as the default profile name

- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
When we uploaded from files, the AWS code would lookup in an internal map from the extension of the file being uploaded. When uploading using an input stream it defaults everything that isn't explicitly set to application/octet-stream. This change inspects the target key and sets the content type from the lookup file.
> Use the AWS mimetype map to replicate prior behaviour

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
I tried to add a unit test but it was getting endless as I had to mock the s3 client.
cc @sihil
> adds a more understandable message to the cloudformation deployment type

- magenta-lib/build.sbt
- project/MagentaBuild.scala
- project/build.properties
- project/plugins.sbt
- riff-raff/build.sbt
Just taking care of some low hanging fruit in preparation for the Play upgrade
> Bump sbt and plugin versions

- riff-raff/app/conf/context.scala
- riff-raff/app/persistence/ContinuousDeploymentConfigRepository.scala
Look up the stage using the instance's tags.
@sihil @philwills
> Use the "table-name-$STAGE" convention for Dynamo table names

- magenta-lib/src/main/scala/magenta/input/RiffRaffYamlReader.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
Use the new native YAML support rather than our poor mans conversion.
> Eliminate YAML conversion

- magenta-lib/src/main/scala/magenta/DeployContext.scala
- magenta-lib/src/main/scala/magenta/Resolver.scala
- magenta-lib/src/main/scala/magenta/graph/DeploymentGraph.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/actors/TasksRunner.scala
- riff-raff/test/deployment/Fixtures.scala
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
Thought I'd leave it but decided to do this rename after all. Hence the separate PR.
> Rename Tasks to DeploymentTasks

- magenta-lib/src/main/scala/magenta/Credentials.scala
- magenta-lib/src/main/scala/magenta/Lookup.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- riff-raff/app/resources/PrismLookup.scala
This is a prelude towards making them configurable in the UI and supporting STS
> Remove some cruft from credentials

- magenta-lib/src/main/scala/magenta/DeploymentPackage.scala
- magenta-lib/src/main/scala/magenta/Resolver.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/ElasticSearch.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/main/scala/magenta/deployment_type/SelfDeploy.scala
- magenta-lib/src/main/scala/magenta/graph/Graph.scala
- magenta-lib/src/main/scala/magenta/graph/package.scala
- magenta-lib/src/main/scala/magenta/input/models.scala
- magenta-lib/src/main/scala/magenta/input/resolver/Resolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/TaskResolver.scala
- magenta-lib/src/test/scala/magenta/DeployContextTest.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/fixtures/fixtures.scala
- magenta-lib/src/test/scala/magenta/fixtures/package.scala
- magenta-lib/src/test/scala/magenta/input/resolver/TaskResolverTest.scala
- riff-raff/app/controllers/Application.scala
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/preview.scala
- riff-raff/app/views/deploy/viewDeploy.scala.html
- riff-raff/app/views/documentation/deploymentTypeSnippet.scala.html
- riff-raff/app/views/menu/menubar.scala.html
- riff-raff/conf/routes
- Add a resolver to build a DeploymentTasks from a Deployment
- Complete the top level Resolver
- Facilitate different defaults for deploy.json / riff-raff.yaml (including documentation)
> Tie together all of the loose ends

- riff-raff/app/views/validation/validationErrors.scala.html
- riff-raff/app/views/validation/validationForm.scala.html
- riff-raff/app/views/validation/validationPassed.scala.html
This provides a better validation UI for my riff-raff.yaml demo this Friday.
> Slightly better validation UI for demoing

- magenta-lib/src/main/scala/magenta/package.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
- riff-raff/conf/logback.xml
This is to help with tracking down why some static files don't seem to be uploading correctly.
> Add some debug and warnings around the S3 upload task

- riff-raff/app/deployment/actors/TasksRunner.scala
The stop flag was only being checked between DeploymentTask blocks and not between each Task. This checks the flag before each task is executed and bails if need be.
> Actually properly fix the stop button (again)

- magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
The code was doing a get on the wrong variable. Regardless I've modified the code so that there is no need to do a get by switching the nested `if` to pattern matching.
Will write some tests later today after my meetings and @adamnfish has shipped Janus.
> Make the reporting of a default parameter more functional

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
Add a param to `UpdateAmiCloudFormationParameterTask` to specify that
stack should be found based on app/stack/stage tags
(based on PR #303)
> Support looking up CloudFormation stack by tags

- riff-raff/app/views/validation/validationPassed.scala.html
> Fix "Actions" label in preview view

- riff-raff/app/views/deploy/viewDeploy.scala.html
I've been trying to think of a good way to do this, but this works
and doesn't have any significant negative impacts.
> Link from deploy to VCS commit

- riff-raff/app/views/snippets/recordTable.scala.html
Haven't really dug into why this is happening:
Either way, this should fix it.
> Hide period if there isn't one to show

- riff-raff/app/assets/javascripts/deploy-verbose.coffee
- riff-raff/app/assets/javascripts/form-autocomplete.coffee
- riff-raff/app/conf/context.scala
- riff-raff/app/views/errorPage.scala.html
- riff-raff/app/views/main.scala.html
- riff-raff/app/views/mainNoAuth.scala.html
- riff-raff/app/views/page.scala.html
- riff-raff/app/views/snippets/analytics.scala.html
There is no data at the moment on how much Riff-Raff is used, in what way, or by whom. This adds some basic tracking which should help inform how features are further developed.
> Add basic mixpanel tracking

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
We've seen a couple of failures today on dotcom. The root cause seems to be a `SocketTimeoutException` and this should trigger a retry in the [default retry policy](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/retry/PredefinedRetryPolicies.java#L161) as the exception cause  is a `STE` and that extends `IOException`. However, this has been hard to diagnose so I'd like to add some more logging to catch the next incident.
> Log AWS SDK retries when they occur

- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/ElasticSearchTasks.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
- project/Dependencies.scala
See https://riffraff.code.dev-gutools.co.uk/deployment/view/e6c09f0d-2e73-46f2-9794-919b8f3512ba?verbose=1 for an example of this in practise.
> Application load balancer support for Autoscaling deploys

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
Reverts guardian/riff-raff#419
> Revert "Allow updates to multiple AMI parameters"

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/artifact/S3ZipArtifact.scala
- magenta-lib/src/main/scala/magenta/json/JsonInputFile.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/json/JsonReaderTest.scala
- project/build.properties
- riff-raff/app/ci/CIBuild.scala
- riff-raff/app/ci/S3Build.scala
- riff-raff/app/ci/S3Tag.scala
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/deployment/LegacyPreview.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/preview/PreviewCoordinator.scala
I saw a couple of failed deploys recently with really unhelpful error messages, so I tried to fix that and fell down a bit of an `Either` shaped rabbit hole.
> Exceptions => Error values

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/artifact/S3ZipArtifact.scala
- magenta-lib/src/main/scala/magenta/json/JsonInputFile.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/json/JsonReaderTest.scala
- project/build.properties
- riff-raff/app/ci/CIBuild.scala
- riff-raff/app/ci/S3Build.scala
- riff-raff/app/ci/S3Tag.scala
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/deployment/LegacyPreview.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/preview/PreviewCoordinator.scala
- riff-raff/test/ci/S3BuildTest.scala
This is a retread of #426 except without the disastrous bug. 
To atone for my sins, I've added a test that should have been there a long time ago and I think made things a bit more robust.
> Either parser tests or death

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
Following-up on #430
From AWS SDK 1.11.106 changelog:
XMLStreamExceptions encountered during XML response parsing that are caused by IOException
are now wrapped in IOException before being thrown so that they are
passed to the configured retry policies.
> Remove custom handling of XMLStreamExceptions

- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/conf/logback.xml
Add some further debug to help understand #438 
/cc @philwills @philmcmahon
> Add further debug and enable existing debug

- riff-raff/app/deployment/actors/DeployGroupRunner.scala
more logging for tracking down #438 
/cc @mbarton @philwills
> Add more debug and ensure UUID of deploy is always logged

- riff-raff/app/conf/context.scala
- riff-raff/app/deployment/DeploymentEngine.scala
So much for the gradual punishment. That should really have been min, not max. Otherwise it'll just go straight to 60.
Meh.
> Yep, that should have been min

- build.sbt
- magenta-lib/src/test/scala/magenta/DeployContextTest.scala
- magenta-lib/src/test/scala/magenta/PackageTest.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/ParamTest.scala
- magenta-lib/src/test/scala/magenta/graph/DeploymentGraphTest.scala
- magenta-lib/src/test/scala/magenta/graph/GraphTest.scala
- magenta-lib/src/test/scala/magenta/input/RiffRaffYamlReaderTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentResolverTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTasksGraphBuilderTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/TaskResolverTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTasksTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
- project/Dependencies.scala
- riff-raff/test/deployment/Fixtures.scala
- riff-raff/test/deployment/actors/DeployCoordinatorTest.scala
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
- riff-raff/test/deployment/preview/PreviewTest.scala
- riff-raff/test/utils/VCSInfoTest.scala
This is aimed at moving to 2.12, but as a first step upgrades all libraries, that have a version published for 2.12 and 2.11, to that version.
> Upgrade a bunch of libraries

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/artifact/S3ZipArtifact.scala
- project/Dependencies.scala
> Remove dependence on scala-io

- project/Dependencies.scala
- riff-raff/app/ci/Builds.scala
- riff-raff/app/ci/ContinuousDeployment.scala
- riff-raff/app/deployment/DeploymentEngine.scala
- riff-raff/app/deployment/Deployments.scala
- riff-raff/app/deployment/LegacyPreview.scala
- riff-raff/app/deployment/actors/DeployCoordinator.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/actors/TasksRunner.scala
- riff-raff/app/utils/ScheduledAgent.scala
- riff-raff/test/deployment/actors/DeployCoordinatorTest.scala
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
This updates to use Box (https://github.com/guardian/box). 
It's deployed to CODE and seems to work OK.
> Agent => Box

- project/Dependencies.scala
- riff-raff/app/ci/Builds.scala
- riff-raff/app/ci/ContinuousDeployment.scala
- riff-raff/app/deployment/DeploymentEngine.scala
- riff-raff/app/deployment/Deployments.scala
- riff-raff/app/deployment/LegacyPreview.scala
- riff-raff/app/deployment/actors/DeployCoordinator.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/actors/TasksRunner.scala
- riff-raff/app/utils/ScheduledAgent.scala
- riff-raff/test/deployment/actors/DeployCoordinatorTest.scala
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
Reverts guardian/riff-raff#456
This has created a number of weird issues that are causing OOMs to occur and make Riff-Raff very unstable.
> Revert "Agent => Box"

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
This sentence isn't true anymore
> Fix cfn documentation

- riff-raff/app/deployment/Deployments.scala
We've seen exceptions due to unchecked access of this map correlated with failure in build polling.
We should dig further into why this occurs, but this should deal with the immediate issue.
> Don't blow up if caches don't contain key to clean up

- LICENSE
- NOTICE
Use the github template and have the license correctly recognised by github.
@satterly
> Fix license

- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
Fix for https://github.com/guardian/riff-raff/issues/482
> Fail the deploy fast when zero s3 artefacts are uploaded

- riff-raff/public/docs/reference/riff-raff.yaml.md
The relationship between deployment names and directories wasn't
immediately obvious to me – this will hopefully add some clarity 
(assuming I understand it correctly now 😜 )
> Update documentation on `deployments` YAML property

- riff-raff/app/views/deploy/viewDeploy.scala.html
Adds the date to the deploy view. 
Live in CODE
https://riffraff.code.dev-gutools.co.uk/deployment/view/a4d3ecdf-83fd-464b-8e22-4236df7adf06
> Add date to deploy view

- project/Dependencies.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/utils/ElkLogging.scala
This ships logs from Riff-Raff into the ELK kinesis stream.
TODO:
> Ship logs to ELK via the kinesis stream

- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
Since https://github.com/guardian/riff-raff/pull/507 was merged, we have seen a few deploys fail with the following error:
```com.amazonaws.services.autoscaling.model.AmazonAutoScalingException: The instance i-xxxxxxx is not in InService or EnteringStandby or Standby.```
After investigating this, it appears that RiffRaff has occasionally been trying to protect instances which were terminating (e.g. due to the tasks undertaken in a previous deploy). This PR filters on InService instances before applying protection, which should avoid the exception mentioned above.
> Only apply instance protection to instances which are InService

- build.sbt
- magenta-lib/src/main/scala/magenta/input/models.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentResolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/Resolver.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
- riff-raff/app/AppComponents.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/controllers/authentication.scala
Reverts guardian/riff-raff#516
There are some `cats` conflicts, I'd suggest upgrading Scanamo to fix them.
> Revert "Update dependencies"

- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
Follow-on update to #504 to handle an additional Change Set status we did not encounter during testing. I've updated the code to use an enum from the AWS SDK as well just for extra clarity.
> Handle CREATE_PENDING status on change sets

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
Indicate what cloudformation permissions are required and remove some dead code.
> Update docs for #504

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
The list of permissions from #520 came out on a single line. Hopefully this fixes it.
> Fix badly formatted list

- riff-raff/app/controllers/Application.scala
- riff-raff/app/migration/Migration.scala
For post-deployLogs migration. Also removed the menu item as I felt self-conscious when I saw the link on chat yesterday 😞
> Re-enable deploysV2

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormationDeploymentTypeParameters.scala
A small update to better document an infrequently used parameter.
> Improve docs on the amiParametersToTags param

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
This was retrying for several minutes even on permanently fatal errors such as missing permissions. This was originally to work around a bug in SDKv1. Since we are now on v2, I've switched this to now uses the underlying default retry policy.
Risks
-----
This might fail fast on errors that **can** be retried. This occurred in the Lambda API due to `Rate exceeded` errors not returning with the designated 429 status code. This is now special cased but there may be others.
> Fix up the logging retry condition for SDK v2

- readme.md
- script/start
To make it easier to run locally.
> add start script

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
I thought I could fix a deploy here that hung but I don't think there is enough data so I've just improved the logging a little and made some no-op rearrangements of the code.
> Minor improvements to CFN update tracking

- riff-raff/public/docs/index.md
https://github.com/guardian/riff-raff/pull/566 wasn't quite correct - I think this is more accurate!
> Correct redeploy docs

- riff-raff/app/deployment/actors/DeployGroupRunner.scala
Since the name "master" is not inclusive, it makes sense to have regular reminders so as not to normalise it.
Although most people don't look at riffraff on a daily basis, it is a good place to put it back in people's minds whenever they do.
This will highlight the offending deploys and put a barber pole pattern on them, which should attract people's attention.
Tested in CODE
--
> add warning message when someone deploys a branch called "master"

- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
It is not possible to update a stack policy for a stack that doesn't yet exist, so don't.
- Deploy `main` to CODE
- Deploy a project that will create a stack
- Witness the deploy fail
- Deploy to CODE
- Deploy a project that will create a stack
- Witness the stack being created and the deploy succeeding
- Deploy the project again and witness the deploy log setting the stack policy
We're able to continue using RiffRaff to create stacks if they do not exist.
n/a
> fix: Only set a stack policy when a stack exists

- build.sbt
- magenta-lib/src/main/scala/magenta/deployment_type/Fastly.scala
- project/plugins.sbt
- readme.md
- riff-raff/app/views/page.scala.html
- riff-raff/app/views/schedule/form.scala.html
- riff-raff/public/docs/riffraff/administration/properties.md
- riff-raff/public/docs/riffraff/externalRequest.md
- riff-raff/public/docs/riffraff/s3buckets.md
- Updates resolver URLs to HTTPS
- Updates links to external resources to HTTPS
> chore: HTTPS all the links

- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
Reverts guardian/riff-raff#651
> Revert "Prevent deletion and replacement of DNS infrastructure"

- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
Ignore instances already in a terminating phase when deciding which instances to terminate during an EC2 deployment.
This should address this occasional error:
```
Your ASG desired size may have been reset Instance Id not found - No managed instance found for instance ID: i-abcdefgh123456789
```
???
Fewer errors and possibly faster deploys as there are fewer instances to affect.
> fix: Do not attempt to terminate twice

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
Improves parameter docs.
See also https://github.com/guardian/riff-raff/pull/632/files#r655291289 which was helpful in me figuring this out when I hit this.
> Improve asgMigrationInProgress docs

- readme.md
In an attempt to ease local development setup for new contributors to riff-raff, I've added a bit more clarity on the required Java version and config file. This was based on some feedback from @rhystmills
> Clarify local dev requirements

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
Following https://github.com/guardian/cdk/pull/1123, and inspired by https://github.com/guardian/riff-raff/pull/237, introduce a new way to define a cloudformation template file. More detail/context can be seen in the [ADR/proposal doc](https://github.com/guardian/cdk/blob/main/docs/architecture-decision-records/006-stage-awareness.md).
This will allow us to:
- produce multiple files (one per stage) with GuCDK
- simplify the GuCDK codebase
- enable GuCDK to support any stage name (previously it only supported CODE, PROD, INFRA)
This is a non-breaking change as, when `templateStagePaths` is not defined, we fallback to `templatePath`.
- Deploy to CODE
- Deploy a build of https://github.com/guardian/cdk-playground/pull/173
This unblocks https://github.com/guardian/cdk/pull/1134. More detail …
> feat: Introduce `templateStagePaths`

- project/build.properties
This resolves an issue encountered when using an M1 Macbook.
See https://github.com/playframework/playframework/issues/10867.
Follow the README instructions to run the app locally (optionally, repeat this on an M1 machine).
We can continue to develop on RIff-Raff locally.
> chore(deps): Update sbt to 1.6.2

- riff-raff/bootstrap.sh
Follows #691, and combined with the current update AMI deployment type, this will ensure Riff-Raff is using a recent AMI.
Schedule is:
- CODE every Wednesday at 8AM
- PROD every Thursday at 8AM
> feat: Perform instance rotation on a schedule

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
This adds support for the `bucketSsmLookup` parameter to the `autoscaling` deployment type, bringing it inline with the `aws-lambda` type.
This change allows Riff-Raff to discover the target S3 bucket from SSM Parameter Store, rather than having the bucket name hardcoded in `riff-raff.yaml`.
We go from:
```yaml
stacks:
- deploy
regions:
- eu-west-1
allowedStages:
- PROD
deployments:
cdk-playground:
type: autoscaling
parameters:
bucket: my-bucket-name
```
To:
```yaml
stacks:
- deploy
regions:
- eu-west-1
allowedStages:
- PROD
deployments:
cdk-playground:
type: autoscaling
parameters:
bucketSsmLookup: true
```
By default Riff-Raff will discover the bucket on the SSM path `/account/services/artifact.bucket`, and it already supports the [`bucketSsmKey` …
> feat: Support `bucketSsmLookup` parameter in autoscaling deployment type

- riff-raff/app/controllers/Management.scala
- riff-raff/bootstrap.sh
- riff-raff/conf/routes
The completion of https://github.com/guardian/riff-raff/pull/691#discussion_r863571762.
> refactor: Rename `rotate` to `terminate` for consistency

- .scala-steward.conf
- project/Dependencies.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/utils/ElkLogging.scala
Reverts guardian/riff-raff#801
> Revert "Dependency updates 2022-08-15"

- contrib/riff-raff-yaml-schema.json
* Adds `actions` to the schema for `DeploymentOrTemplate`
> Add actions to schema for DeploymentOrTemplate

- contrib/riff-raff-yaml-schema.json
Updates the schema file to deep-link to the correct branch following a rename.
> chore: Update deep-link following default branch rename

- magenta-lib/src/main/scala/magenta/deployment_type/BucketParameters.scala
To support using a different SSM path per stage. Especially useful to allow us to remove Deployment Resources, which are used in part for this reason.
Once merged, we can migrate the few uses of S3-related deployment resources, and merge https://github.com/guardian/riff-raff/pull/941.
> Introduce bucketSsmKeyStageParam

- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
Builds on https://github.com/guardian/riff-raff/pull/942, which provides an alternative to S3 resource-based parameters, to do two things:
1) support SSM parameters for S3 deployments
2) remove support for resource parameters (`bucketResource`, `pathPrefixResource`)
Note, *only `pathPrefixResource` has been removed here* but `bucketResource` will be removed as a follow-up once the affected team have migrated. Resource parameters are virtually unused and are better served through the more general SSM parameters (`bucketSsmKey`, or `bucketSsmKeyStageParam`).
This PR is inspired by https://github.com/guardian/riff-raff/pull/893, which it now supercedes. Thanks to @philmcmahon for the hard work on that.
> Extend aws-s3 deployment type to support bucket SSM parameters

- .github/workflows/ci.yml
- build.sbt
- magenta-lib/src/main/scala/magenta/deployment_type/LambdaLayer.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- project/Helpers.scala
- script/ci
It turns out the CI script that applied `scalafmt` was no longer in use - I've updated the correct place and reformatted to account for changes since the original scalafmt application.
> Fix ci - and remove outdated ci script

- riff-raff/app/persistence/IAMPasswordProvider.scala
Minor improvement - think I hit this when testing Postgres 12 on code but difficult to tell without any logging!
> Log error when unable to fetch db password

- CONTRIBUTING.md
This mentions the required permissions for running locally in the Contributing doc.
> Mention required permissions in contributing doc

- magenta-lib/src/main/scala/magenta/deployment_type/BucketParameters.scala
- magenta-lib/src/test/scala/magenta/deployment_type/BucketParametersTest.scala
Just changed wording of error message
ci passing should suffice
> Clarify commit message about exposed bucket names

- riff-raff/app/ci/S3Build.scala
We want to enforce a relation between repository and project (at least). As a pre-requisite, this change adds some structured logging on each successful parsing of the `build.json` files. We can these use these logs to understand which projects, if any, might be impacted by the aforementioned restriction.
Deploy to CODE, and [observe the logs](https://logs.gutools.co.uk/s/devx/goto/d2f3a060-db12-11ee-9631-efa6837e8b86).
> feat: Add structured logs on successful parsing of `build.json`

- riff-raff/app/conf/context.scala
A no-op change for consistency.
> Consistently use aliased import

- riff-raff/app/notification/DeployFailureNotifications.scala
DevX maintain some projects which are deployed to several AWS accounts.
If a deployment for one of these projects fails, Riff-Raff will send [Anghammarad](https://github.com/guardian/anghammarad) a huge list of targets (e.g. 10 different AWS accounts, 10 different Stacks, 3 different Apps[^1]). As a result, the failure notifications are often sent to surprising Chat channels/email addresses! For example, prior to this PR `devx::aws-account-setup` alerts were always being sent to `P&E/Content Production 🗞️🛠️` (sorry!).
We have [previously tried](https://github.com/guardian/anghammarad-config/pull/33) to override this behaviour using more precise Anghammarad config, but we now know that this will not work in all scenarios due to the [parsing logic in …
> Send notifications for multi-account DevX projects to the correct place

- project/Dependencies.scala
To bring in [this change](https://github.com/guardian/anghammarad/pull/307), which should fix some notifications for the DevX Reliability & Operations team.
> Upgrade Anghammarad version

- riff-raff/public/docs/riffraff/administration/auth.md
This PR expands the documentation about Google Auth to help future travellers tasked with rotating its secrets.
> Add explanation about how to rotate secrets

- riff-raff/public/docs/riffraff/administration/auth.md
Based on [this retro doc](https://docs.google.com/document/d/17rPcdh2KUffO9s2rpkbOSv1DzgOFuhkkEOQI3W4pCGQ/edit?tab=t.0#heading=h.g7lvu14f1vc2).
> Add comms step to key rotation docs
