- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
This leaves the loadbalancer at "double" size for a configurable number of seconds to give the instances time to warm up.
We never realised it, but the 2nd `HealthcheckGrace` (recently removed) was fulfilling this function for us, hence crash and burn when deploying under load today.
@sihil @philwills (please)
> Added a "warmup" grace period.

- build.sbt
- magenta-cli/build.sbt
- project/MagentaBuild.scala
- project/plugins.sbt
- riff-raff/build.sbt
The latest version of sbt-assembly works as an auto-plugin which reduces boilerplate. The move to `assemblyProperty in assembly` is a bit ugly mind.
> SBT assembly as auto-plutgin

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/json/JValueExtractable.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
Introduces a new property `templateStageParameters` which supports stage-specific parameters. Currently parameters must be the same across stages, which is somewhat limiting.
Riff Raff will look for a key in the property's map matching the stage of the deployment. If found, it will merge the contained parameters into `templateParameters` (the global parameters if you like), with
stage-specific keys overriding global ones in case of collision.
@philwills @sihil what are your thoughts on this? Happy to discuss.
> Support stage-specific params for cfn deployment types

- cloudformation/riffraff.template
The idea is that once we've done this, any builds which a team wants to make just need to create their own credentials to upload to the buckets.
I don't see a way to apply the same policy to multiple buckets, which is annoying.
cc @sihil
> Allow fronts tool account access to buckets

- cloudformation/riffraff.template
Grant access to identity account for uploading to riffraff S3 buckets.
> Allow riffraff uploads for identity account

- cloudformation/riffraff.template
We want to try uploading our own artefacts to the bucket.
> Allow Discussion account access to RiffRaff S3 bucket

- magenta-lib/build.sbt
- magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
Adds a deployment type `aws-lambda` which provides one deploy action, `updateLambda`, that runs Lambda Update Function Code using the package files which can be specified per stage.
CC @guardian/discussion @philwills
> Lambda deployment type

- riff-raff/app/controllers/authentication.scala
- riff-raff/build.sbt
I discovered today that riff-raff has not been applying Authorisation correctly. I suspect this happened when it was converted to the play-googleauth library as the authorisation code was massively overhauled.
Anyhow - this one little trick applies the authorisation check.
> Check whether a user is authorised

- riff-raff/app/views/errorPageException.scala.html
Upon receiving an exception on the riffraff deploy screen, the exception lines are meant to print out with newlines in between, but this doesn't work and the browser just ignores the newlines. You receive just a big long string.
This wraps each exception line in a `span`.
> Format exception lines nicely in the browser

- magenta-lib/build.sbt
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
I've gone for readability over brevity and even with the imports it's barely bigger than the regex.
> NO MORE REGULAR EXPRESSIONS.

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
The AWS SDK now makes it possible to specify in an update call to a cloudformation stack that existing values should be reused.
This PR changes the behaviour so that this flag is automatically set for any parameter in a cloudformation template that has neither a default value, a value provided by the user nor a value generated by riff-raff itself (eg. Stack/Stage).
This following screenshot illustrates this at work. The CertificateARN parameter has no default or anything specified so is passed in as UseExistingValue.
> Use existing CloudFormation params

- magenta-lib/build.sbt
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
If the template file has a `.yml` or `.yaml` extension, it is assumed to be in YAML format and RiffRaff will convert it to JSON on the fly. Otherwise it is assumed to be in JSON format and will be used as-is.
> Add support for YAML CloudFormation templates

- build.sbt
- riff-raff/app/persistence/mongodb.scala
- riff-raff/build.sbt
compose.io provides MongoDB 3.2.1 so the libraries we use must be compatible with that version. We're bumping to the latest version of Casbah as there is no reason to do otherwise.
> Bump Casbah so that we work with MongoDB 3.2.1

- magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
- magenta-lib/src/main/scala/magenta/deployment_type/SelfDeploy.scala
- project/MagentaBuild.scala
- project/plugins.sbt
- riff-raff/app/conf/context.scala
- riff-raff/app/views/page.scala.html
- riff-raff/conf/deploy.json
Make self deployment work inside the AWS environment.
This is connected with two other PRs: https://github.com/guardian/machine-images/pull/95 and https://github.com/guardian/deploy-tools-platform/pull/10. 
This PR also makes the build ID visible again at the bottom right of each page:
> Self deployment and version visibility

- riff-raff/app/Global.scala
- riff-raff/app/utils/HstsFilter.scala
I'm somewhat bored forgetting to type https at the start of the Riff-Raff URL. This should fix that, after the first visit and I think a smarter than forwarding from HTTP.
> Return an HSTS header if we are behind an HTTPS proxy (ie. an ELB)

- riff-raff/app/utils/HstsFilter.scala
The spec ignores HSTS headers when not on TLS connections so we can send the header with impunity.
> Simplify HSTS header

- riff-raff/app/notification/hooks.scala
The current logging catches HTTP errors, but not network errors.
> Log an error when a hook fails

- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
The `get` call doesn't ever return defaults, so switch to `apply` since we know it will never be None in this case as there is a default.
> Handle default value of fileNameParam correctly

- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
The `S3Upload` task does a little too much internally which makes it hard to reason about and hard to use when you want to reliably work out where it has uploaded files. The replacement V2 doesn't do as much magic and moves the responsibility of mapping files to keys (or directories to key prefixes) to the callee.
At the moment I've only replaced the use of it in the lambda upload action, but would like to completely replace and remove `S3Upload`.
> Replace the S3Upload task with a new S3UploadV2 task

- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
The restructured `S3Upload` task broke mobile's static file deploy as we inject a superfluous `/` into the key when a zero length prefix is provided (see https://riffraff.gutools.co.uk/deployment/view/1cbf487f-89c7-46c9-8cbe-2b5facc27eed?verbose=1).
This fix special cases the zero length key.
> Cater for case with zero length prefix

- magenta-lib/src/main/scala/magenta/logging.scala
- riff-raff/app/deployment/actors.scala
Since #293 failed deployed have not correctly been shown as that. This is because of the move away from `withContext` which used to handle cleanup. I've now renamed that to `withFailureHandling` and reintroduced it into the key locations in `TaskRunner`.
> Fix failed deploy reporting

- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
The parameter is quite similar to the `bucketResource` key, but changes the path, rather than the bucket, that the resources get deployed to.
This will allow us to deploy files into differing locations in the `gdn-cdn` S3 bucket, ie:
https://interactive.guim.co.uk/2016/05/brexit-companion/
https://interactive.guim.co.uk/testing/2016/05/brexit-companion/
...the addition of `/testing/` appears to be a convention on the Visuals team, eg: https://github.com/guardian/interactive-brexit-companion/blob/530c4ad/Gruntfile.js#L125-L151
https://riffraff.gutools.co.uk/deployinfo/data
cc @sihil @DiegoVazquezNanini @annebyrne
> Enable a configurable `pathPrefixResource` for `aws-s3` upload deployments

- riff-raff/app/assets/stylesheets/magenta.less
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/views/deploy/deployConfirmation.scala.html
- riff-raff/app/views/deploy/viewDeploy.scala.html
- riff-raff/conf/routes
Adds a Deploy Again button to the /deploy/view/:uuid view (Fixes #168). This will add a new deploy (new uuid) with the same parameters as the deploy in view.
Some notes: 
* Button is present for both failed and successful builds
* As we don't seem to deploy to specific hosts anymore I haven't included this in parameters to pass to the form. @sihil should I?
cc/ @sihil @alexduf
> Deploy again feature

- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
With this change, when a `pathPrefixResource` is found, the `prefixStage`, `prefixPackage` and `prefixStack` keys are ignored and only the looked-up prefix is used, ie:
`/<pathPrefix>/<filePathAndName>`
The old, broken paths had `//` in them (eg `s3://gdn-cdn/testing/2016/05/brexit-companion//embed/embed.html`):
This follows on from #302, which introduced `pathPrefixResource` configuration.
cc @philwills @SiAdcock
> Fix S3 deploy paths, removing double-slashes ('//')

- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
To be able work with multiple stacks we need to be able to prepend the stack name to a lambda function name. This will only be set if `prefixStack` is set to true. 
@sihil I've added a test as per our discussion.
> Prefix the lambda with stack name if prefixStack is set to true

- riff-raff/app/assets/js/history-dropdown.coffee
i.e. prevent the Hash of Doom from breaking the project name filter.
I'm still not sure where that hash comes from, but this should make the URL manipulation resilient to its presence.
You're welcome, every Riff Raff user ever.
> Make the project filter on deploy history page work reliably

- magenta-lib/src/main/scala/magenta/reporting.scala
- riff-raff/app/utils/DateFormats.scala
- riff-raff/app/views/api/list.scala.html
- riff-raff/app/views/auth/list.scala.html
- riff-raff/app/views/continuousDeployment/list.scala.html
- riff-raff/app/views/deploy/buildInfo.scala.html
- riff-raff/app/views/hooks/list.scala.html
- riff-raff/app/views/snippets/pimpedBuildId.scala.html
- riff-raff/app/views/snippets/recordTable.scala.html
- riff-raff/app/views/test/s3Latencies.scala.html
Date formatting was quite inconsistent across the app, e.g.:
* Deploy start time was in London time (actually browser locale's time, I think) on the history page, but the deploy logs were in UTC.
* API keys, etc. had their dates formatted in US style (mm/dd/yy)
There is an argument for displaying all timestamps in UTC, but given that nearly all users are in London, I think London time is more convenient. As long as we are consistent (which we now should be), it doesn't really matter which one we pick.
> Consistently display timestamps in London time, UK locale

- magenta-lib/build.sbt
When we switched to a user key it broke fastly deploys as it relies on a different header. The newer version of the fastly client fixes this.
> Bump the fastly client to use the correct HTTP header

- magenta-lib/src/main/scala/magenta/Project.scala
- magenta-lib/src/main/scala/magenta/Resolver.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
- magenta-lib/src/main/scala/magenta/deployment_type/ElasticSearch.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Fastly.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/main/scala/magenta/deployment_type/SelfDeploy.scala
- magenta-lib/src/test/scala/magenta/DeployContextTest.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- magenta-lib/src/test/scala/magenta/fixtures/fixtures.scala
- magenta-lib/src/test/scala/magenta/fixtures/package.scala
This will make it less intrusive to make other more significant changes (adding more resources to this case class is easier than changing every deployment type).
> Refactor deployment type by introducing resources and target classes

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/artifact/S3ZipArtifact.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
Magenta-lib was buffering the whole file in memory when downloading artifacts and uploading to S3. With the recent changes memory pressure will have increased somewhat - this removes the needless use of memory when handling streams.
> Avoid buffering in memory when downloading and uploading files

- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
When we are uploading thousands of files this behaviour puts a strain on the DB. A handful of files is useful for debugging, but logging everything is superfluous so lets just do the first 10.
> Don't log more than 10 files in detail

- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/views/deploy/viewDeploy.scala.html
- riff-raff/conf/routes
It's pretty difficult to view the deploy.json without accessing the S3 bucket. I'd like to expand this to a debug view for a build, but this is an easy starting point that only took a few minutes but will none the less be useful.
> Add a way of instantly seeing the associated deploy.json

- riff-raff/app/deployment/actors.scala
- riff-raff/build.sbt
- riff-raff/test/deployment/DeployCoordinatorTest.scala
A brittle part of the Riff-Raff codebase is the `DeployCoordinator` Finite State Machine. This adds some tests around it to test some of the basic functionality. A couple of minor tweaks to the codebase have been made in order to make it possible to get a test harness around it easily.
> Tests around the DeployCoordinator FSM

- magenta-lib/src/main/scala/magenta/DeployContext.scala
- magenta-lib/src/main/scala/magenta/Resolver.scala
- magenta-lib/src/main/scala/magenta/graph/DeploymentGraph.scala
- magenta-lib/src/main/scala/magenta/graph/Graph.scala
- magenta-lib/src/main/scala/magenta/graph/package.scala
- magenta-lib/src/test/scala/magenta/DeployContextTest.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/graph/DeploymentGraphTest.scala
- magenta-lib/src/test/scala/magenta/graph/GraphTest.scala
- magenta-lib/src/test/scala/magenta/graph/SimpleGraphTest.scala
- riff-raff/app/deployment/actors.scala
- riff-raff/app/deployment/preview.scala
- riff-raff/test/deployment/DeployGroupRunnerTest.scala
- riff-raff/test/deployment/Fixtures.scala
In preparation for overhauling the resolver I've made the new graph type I built generic and made it somewhat more fully featured. 
Making it generic makes it possible to map from a graph of one type to a graph of a different type - for example this makes it possible to resolve a graph of recipes as the first step and then map the recipes into deployments as a second step rather than doing everything at once.
I've also moved priority onto the edge instead of the node. Turns out that it makes merging graphs like the following much easier as nodes are easily discoverable within the edges and nodes without having to workaround priorities. Other methods are easier to implement too.
This was originally done to deal with cases like the below. Whilst this is contrived it does deal with cases …
> Make graph implementation generic and add new methods

- magenta-lib/src/main/scala/magenta/Resolver.scala
- magenta-lib/src/main/scala/magenta/graph/Graph.scala
- magenta-lib/src/main/scala/magenta/graph/package.scala
- magenta-lib/src/test/scala/magenta/graph/GraphTest.scala
When I was experimenting with building smarter graphs with the resolver (abandoned for now) I found various bugs and fixed them.
- various improvements to the graph library to behave correctly in a number of corner cases when merging or flattening graphs
- added clear methods for gaining access to edges
- changed `map` to work with underlying types
- add easy to read toString method on graph class
- add numerous tests to cover more corner cases
- add `toGraph` to the `RecipeTasksNode` to build a graph from tree of nodes
> Fix various bugs in the graph library

- magenta-lib/src/main/scala/magenta/package.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/PackageTest.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
The retry logic in the AWS SDK is flawed when uploading an InputStream that cannot be reset. 
This moves the retry logic for this case outside of the SDK call so that the InputStream can also be reset. The internal retry logic is disabled by passing in a `ClientConfiguration` with a no retry policy. We continue to use the AWS retry and backoff logic from the client configuration - you'll note that the `originalRequest` is not passed in as we do not have it and neither is it actually used.
> Retry failed S3 uploads when using InputStream

- magenta-lib/src/main/scala/magenta/Resolver.scala
- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/logging.scala
- magenta-lib/src/main/scala/magenta/reporting.scala
- riff-raff/app/assets/stylesheets/magenta.less
- riff-raff/app/controllers/Testing.scala
- riff-raff/app/deployment/preview.scala
- riff-raff/app/persistence/package.scala
- riff-raff/app/persistence/representation.scala
- riff-raff/test/RepresentationTest.scala
- riff-raff/test/Utilities.scala
It's been an aim of mine for a while to have a way of pushing people to migrate from deprecated configurations. I've added a reporter message type of warning which is highlighted beautifully and can be used to give deprecation warnings.
I've added a handful of things to highlight as deprecation warnings:
- `publicReadAcl=true` on an autoscaling deploy
- Not uploading via S3 when updating lambdas
- Not having `defaultStacks` in a deploy.json
- Using the artifacts.zip format
An example:
> Add deprecation warnings for deploy.json configs

- magenta-lib/src/main/scala/magenta/input/DeploymentResolver.scala
- magenta-lib/src/main/scala/magenta/input/RiffRaffYamlReader.scala
- magenta-lib/src/main/scala/magenta/input/models.scala
- magenta-lib/src/test/scala/magenta/input/DeploymentResolverTest.scala
This commit addresses the points I raised in my review of [the `riff-raff.yaml` proposal PR](https://github.com/guardian/riff-raff/pull/342).
* handles missing required fields in deployments
* makes use of scalatest's EitherValues trait
* passes a context in the Left of the Either to enable display of which block the error refers to
It also:
* simplifies the DeploymentResolver logic
* separates the models from the business logic
* documents the DeploymentOrTemplate model
> Update to the riff-raff.yaml proposal

- magenta-lib/src/main/scala/magenta/input/DeploymentResolver.scala
- magenta-lib/src/main/scala/magenta/input/RiffRaffYamlReader.scala
- magenta-lib/src/main/scala/magenta/input/models.scala
- magenta-lib/src/test/scala/magenta/input/DeploymentResolverTest.scala
- magenta-lib/src/test/scala/magenta/input/RiffRaffYamlReaderTest.scala
- project/Dependencies.scala
- project/plugins.sbt
This implements a parser for the `riff-raff.yaml` [proposal](https://docs.google.com/document/d/1zUQz8cHj8WbcZ-JgbFhtWteFgYtiTCmW771SELxZ5S8/edit).
It consists of two parts, a RiffRaffYamlReader and a DeploymentResolver. The reader turns the YAML in to a set of case classes that map directly from the YAML format. The resolver takes the representation provided by the first and produces a list of deployments by applying the templates and defaults.
None of this is actually hooked up to anything else, but I think makes sense to review on its own.
Reader
-------
The reader converts the YAML to JSON and then uses the Play JSON library. I tried using some YAML libraries to no avail. Someone is welcome to try again if they so desire, but this works well given that the format is a subset of JSON. …
> Parser for riff-raff.yaml proposal

- project/plugins.sbt
We should really migrate ourselves onto the non-legacy artifact format.
> Bump sbt-riffraff-artifact plugin to use new format

- magenta-lib/src/main/scala/magenta/Project.scala
- magenta-lib/src/main/scala/magenta/Resolver.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
- magenta-lib/src/main/scala/magenta/deployment_type/ElasticSearch.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Fastly.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/main/scala/magenta/deployment_type/SelfDeploy.scala
- magenta-lib/src/main/scala/magenta/json/JsonInputFile.scala
- magenta-lib/src/test/scala/magenta/DeployContextTest.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- magenta-lib/src/test/scala/magenta/fixtures/fixtures.scala
- magenta-lib/src/test/scala/magenta/fixtures/package.scala
- magenta-lib/src/test/scala/magenta/json/JsonReaderTest.scala
- riff-raff/app/views/deploy/previewContent.scala.html
Per-host actions are barely used anymore so this removes the concept from the codebase.
The single remaining place this was used was for Riff-Raff's own self-deployment mechanism which has been re-written to do the host lookup within the deployment type.
> Remove per-host actions concept

- magenta-lib/src/main/scala/magenta/Resolver.scala
- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
This improves the publicReadAcl so that the deprecation warning only happens when it is not set at all. If a project explicitly sets it to true then we don't display the warning.
We make the message clearer as well.
This depends on https://github.com/guardian/sbt-riffraff-artifact/pull/27
> Improve the deprecation messaging and also the publicReadAcl check

- riff-raff/app/AppLoader.scala
- riff-raff/app/ci/Builds.scala
- riff-raff/app/ci/ContinuousDeployment.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/deployment/Deployments.scala
- riff-raff/app/lifecycle/Lifecycle.scala
- riff-raff/app/lifecycle/ShutdownWhenInactive.scala
- riff-raff/app/notification/hooks.scala
- riff-raff/app/persistence/housekeeping.scala
- riff-raff/app/utils/ScheduledAgent.scala
A couple of problems have combined to mean that post deploy hooks haven't been working for a while.
- Some actor wiring was slightly off since the Play 2.5 upgrade
- The role permissions needed to grant access to the index - done in https://github.com/guardian/deploy-tools-platform/pull/46
I've also tidied up the `Lifecycle` traits.
> Fix post deploy hooks

- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
The associated changes add the capability to deploy a lambda in multiple regions which can be specified in the deployment configuration file.
If not provided, `eu-west-1` region (the current default) is used.
> Add the ability to deploy lambda cross-regions

- magenta-lib/src/main/scala/magenta/tasks/FastlyTasks.scala
#354 didn't correctly fix up the Fastly status check. This fixes the error and also adds a warning check.
> Fix JSON parsing of fastly response and add unhappy case warning

- magenta-lib/src/main/scala/magenta/graph/DeploymentGraph.scala
- magenta-lib/src/main/scala/magenta/graph/Graph.scala
- magenta-lib/src/main/scala/magenta/graph/package.scala
- magenta-lib/src/main/scala/magenta/input/RiffRaffYamlReader.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentGraphActionFlattening.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentGraphBuilder.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentResolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentTypeResolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/Resolver.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/graph/DeploymentGraphTest.scala
- magenta-lib/src/test/scala/magenta/graph/GraphTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentGraphActionFlatteningTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentResolverTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTasksGraphBuilderTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTypeResolverTest.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
From a list of deployments with dependencies we should build a graph of deployments. This is achieved using a graph builder that creates all of the necessary edges to fulfil the deployments. We create three sets of edges:
- from the `StartNode` to all nodes that have no listed dependencies (i.e. nothing goes before them)
- from a dependency node to a dependent node (i.e. each edge that is expressed by an entry in a deployment's dependencies list)
- from any node on which no nodes depend to the `EndNode`
These three sets joined together creates a complete graph for the Deployments.
It was realised that building a graph at this stage only makes sense if we can make later transformations easy. As such this PR also implements a `flatMap` on `Graph` that allows individual nodes to be replaced …
> Build a deployment graph from a list of deployments

- magenta-lib/src/main/scala/magenta/DeploymentPackage.scala
- magenta-lib/src/main/scala/magenta/input/resolver/TaskResolver.scala
- magenta-lib/src/main/scala/magenta/json/JsonInputFile.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- magenta-lib/src/test/scala/magenta/fixtures/package.scala
- magenta-lib/src/test/scala/magenta/json/JsonReaderTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTasksTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
The field on this case class was never set in the case where it _wasn't_ a `legacyConfig`. Thus everything was treated as if it was a legacy configuration. This is a lesson to not use a default parameter in order to avoid updating all of the tests.
> I must never use a default parameter for a critical flag

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
- magenta-lib/src/main/scala/magenta/deployment_type/ElasticSearch.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/main/scala/magenta/deployment_type/SelfDeploy.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentTypeResolver.scala
- magenta-lib/src/test/scala/magenta/DeployContextTest.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/fixtures/fixtures.scala
- magenta-lib/src/test/scala/magenta/fixtures/package.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTypeResolverTest.scala
In the new riff-raff.yaml world we:
- Error fast when a required parameter is missing
- Error when a parameter is supplied that is not used by the deployment type
- Log a warning when a parameter is explicitly set to the default value of the parameter
> Numerous parameter validation improvements

- magenta-lib/src/main/scala/magenta/deployment_type/param_reads/PatternValue.scala
- magenta-lib/src/main/scala/magenta/input/RiffRaffYamlReader.scala
- magenta-lib/src/main/scala/magenta/input/models.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentResolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentTypeResolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/Resolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/TaskResolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/package.scala
- magenta-lib/src/main/scala/magenta/package.scala
- magenta-lib/src/test/scala/magenta/fixtures/ValidatedValues.scala
- magenta-lib/src/test/scala/magenta/input/RiffRaffYamlReaderTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentGraphActionFlatteningTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentResolverTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTasksGraphBuilderTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTypeResolverTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/TaskResolverTest.scala
- project/Dependencies.scala
- riff-raff/app/controllers/Application.scala
- riff-raff/app/controllers/api.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/views/validation/validationErrors.scala.html
- riff-raff/app/views/validation/validationForm.scala.html
- riff-raff/app/views/validation/validationPassed.scala.html
- riff-raff/conf/logback-dev.xml
- riff-raff/conf/routes
This makes much of the code a bit cleaner and easier to reason about and in come cases means that we can return multiple errors. As a bonus some of the Json reads code becomes a little easier to reason about as well.
This adds an API endpoint to which YAML can be sent for validation and some **very** rudimentary web pages that let you do the same (your eyes will hurt!)
Would be interested in doing a code review of all of this in person with anyone who has used cats before.
> Switch to ValidatedNel / Validated instead of Either

- magenta-lib/src/main/scala/magenta/input/RiffRaffYamlReader.scala
- magenta-lib/src/main/scala/magenta/input/models.scala
- magenta-lib/src/main/scala/magenta/input/package.scala
- magenta-lib/src/test/scala/magenta/input/RiffRaffYamlReaderTest.scala
If a field is provided that we are not using then this is probably a bad thing. In many cases it will be because someone has made a typo (e.g. they may have used `template` instead of `templates`). This is another opportunity to fail fast to make life easier for users.
> When parsing the YAML check for extra fields

- riff-raff/app/assets/javascripts/auto-refresh.coffee
- riff-raff/app/assets/javascripts/notifications.coffee
- riff-raff/app/views/deploy/logSummary.scala.html
- riff-raff/app/views/deploy/viewDeploy.scala.html
The user will be prompted to allow or reject notifications on the first deployment. Users can disable notifications later by modifying their browser authorisations.
The appearance will vary depending on your system.
> Enable desktop notification upon deployment

- riff-raff/app/AppLoader.scala
- riff-raff/app/assets/javascripts/stop-deploy.coffee
- riff-raff/app/views/deploy/stopDeployButton.scala.html
I had a couple of reports of this not working. The reason was the the AJAX stop call was being nixed by the global CSRF filter.
This change isn't perfect but probably good enough for now - we extract the token from the input field and submit it in the AJAX call.
> Fix the stop button by adding CSRF handling

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
- magenta-lib/src/main/scala/magenta/deployment_type/ElasticSearch.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/main/scala/magenta/deployment_type/SelfDeploy.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentTypeResolver.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTypeResolverTest.scala
- riff-raff/app/controllers/Application.scala
- riff-raff/app/views/documentation/deploymentTypeSnippet.scala.html
I had been overly enthusiastic about parameter validation and it turned out that there are some cases in which no default is specified and that's still OK (i.e. the parameter has no default but is optional). One of these cases is when there are two parameters and you need to set one and only one of these.
This adds an optional field and also enhances the withDefault functionality to provide the DeployTarget instance - this means that we can shift more default logic into the parameters and make fewer params optional when really they default from stack or some such deploy time data.
> Further improve parameter validation

- magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Param.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/ParamTest.scala
As promised in #377 here are some tests for the `Param` class.
I've also moved `Param` into a separate file.
> Move Param classes into own file and write some tests

- magenta-lib/src/main/scala/magenta/DeploymentPackage.scala
- magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Param.scala
- magenta-lib/src/main/scala/magenta/input/resolver/Resolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/TaskResolver.scala
- magenta-lib/src/main/scala/magenta/json/JsonInputFile.scala
- magenta-lib/src/test/scala/magenta/DeployContextTest.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/ParamTest.scala
- magenta-lib/src/test/scala/magenta/fixtures/fixtures.scala
- magenta-lib/src/test/scala/magenta/fixtures/package.scala
- magenta-lib/src/test/scala/magenta/input/resolver/TaskResolverTest.scala
- magenta-lib/src/test/scala/magenta/json/JsonReaderTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTasksTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/controllers/Application.scala
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/controllers/api.scala
- riff-raff/app/deployment/DeploymentEngine.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/preview.scala
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
Whilst writing the YAML preview pages I realised that eliminating the use of the `DeploymentType.all` global would make the code clearer and (naturally) make it easier to test.
This also ties up a loose end where the code still used `ValidatedNel` instead of `Validated` and the `ConfigErrors` semigroup.
> Eliminate use of DeploymentType.all global

- riff-raff/app/controllers/Application.scala
- riff-raff/app/docs/DeployTypeDocs.scala
- riff-raff/test/docs/DeployTypeDocsTest.scala
Sadly broke the deployment type page earlier. I've fixed this and also extracted the rather gnarly logic into a separate object that can be more easily tested. And written a couple of tests to do exactly that.
> Provide the real deployment type name

- riff-raff/app/AppComponents.scala
- riff-raff/app/ci/ContinuousDeployment.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/controllers/Application.scala
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/controllers/Restrictions.scala
- riff-raff/app/controllers/api.scala
- riff-raff/app/controllers/authentication.scala
- riff-raff/app/deployment/Deployments.scala
- riff-raff/app/deployment/model.scala
- riff-raff/app/persistence/RestrictionConfigDynamoRepository.scala
- riff-raff/app/restrictions/RestrictionChecker.scala
- riff-raff/app/restrictions/RestrictionConfig.scala
- riff-raff/app/restrictions/RestrictionForm.scala
- riff-raff/app/restrictions/RestrictionsConfigRepository.scala
- riff-raff/app/views/restrictions/form.scala.html
- riff-raff/app/views/restrictions/list.scala.html
- riff-raff/conf/routes
- riff-raff/test/restrictions/RestrictionCheckerTest.scala
On of the features of Frontend's `goo` wrapper around riff-raff is the ability to block deploys. In addition @adamnfish has expressed a desire to lock down the ability to deploy Janus. 
This goes someway to achieve both of these and hopefully provide just enough flexibility that it will be useful more widely for temporarily blocking deploys.
Further features could be added (or moved to issues for future consideration):
- Nothing currently stops someone creating a new continuous deploy for a restricted project that permits continuous deployments
- Link from a deploy to create a restriction
- Indication of restriction as soon as you enter the project on the deploy screen
> Add restrictions for preventing undesirable deploys

- magenta-lib/src/main/scala/magenta/DeployContext.scala
- magenta-lib/src/test/scala/magenta/DeployContextTest.scala
- riff-raff/app/assets/javascripts/auto-refresh.coffee
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
A couple of tweaks for things that I noticed were broken - the running percentage in the history view and the auto scrolling when viewing a deploy. This should make it somewhat more usable.
The percentage was broken as the YAML based deploys didn't report the total number of tasks to undertake so therefore a percentage couldn't be computed. To solve this we move the responsibility of reporting this into the `DeployGroupRunner` rather than a side effect in the legacy resolver.
The auto scrolling was broken due to change in behaviour - possibly only on retina machines? Either way changing the way we compute the height of the browser viewport solved the issue.
> UI improvements

- magenta-lib/src/main/scala/magenta/input/models.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentGraphActionFlattening.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentPruner.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentResolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentTypeResolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/TaskResolver.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentGraphActionFlatteningTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentPrunerTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentResolverTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTasksGraphBuilderTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTypeResolverTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/TaskResolverTest.scala
- project/Dependencies.scala
- riff-raff/app/controllers/api.scala
Actions are necessary for a deployment and this was enforced by the validation, but not previously reflected in the types.
> Make actions a NEL for a fully resolved Deployment

- magenta-lib/docs/magenta-lib/concepts/index.md
- magenta-lib/docs/magenta-lib/howto/index.md
- magenta-lib/docs/magenta-lib/index.md
- riff-raff/app/controllers/Application.scala
- riff-raff/public/docs/riffraff/administration/index.md
- riff-raff/public/docs/riffraff/index.md
The relative links in the `index.md` files don't have the suffix `.md` and return a 404.
Eg.:
This is an attempt to repair the broken links.
cc @sihil
> Fix relative links in index.md

- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
@johnduffell had some issues with an ASG deploy the other day. Understanding what happened was difficult due to the lack of information surfaced by Riff-Raff. This PR adds a bunch of extra logging but also fixes a potentially dangerous bug in `CheckForStabilization`.
`CheckForStabilization` previously checked whether the ASG was stable and then allowed the deployment to proceed regardless of the outcome of the check. The deployment will now fail with a helpful error.
> Fixes and improved logging for ASG deployments

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
This really follows up on #385 which made it possible to find a cloudformation stack by tags instead of by name in the `AmiCloudFormationParameter` deployment type. This does the same for the `CloudFormation` deployment type as well.
Whilst doing this work I noticed that the cloudformation deployment types ignored the region specification in the new riff-raff.yaml file so I've modified the tasks and client creation to facilitate this. Whilst doing this re-structure I moved the AWS Cloudformation object into same file as the rest of the AWS API wrappers.
In addition I've improved some of the documentation and centralised some logic that creates the lookup strategy.
It will help slightly to view this PR with `w=1` to hide whitespace only changes.
> Add region and tag handling to Cloudformation

- riff-raff/app/utils/VCSInfo.scala
- riff-raff/test/utils/VCSInfoTest.scala
Also got rid of support for the ancient realm of `git.gudev.gnl` and moved to URI instead of URL because URL does blocking DNS lookups.
> Support Github HTTPS URLs

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- project/Dependencies.scala
If a template body is larger than 50kB in size (51200 bytes) then we cannot use the CloudFormation SDK's `templateBody`. Instead we must upload the template to S3 and use `templateUrl` instead.
In order to avoid dealing with more bucket configuration my suggestion is that we create a unique bucket for the purpose of temporarily storing these templates. This PR creates buckets with the name: `riff-raff-cfn-templates-<accountNumber>-<region>` (with a lifecycle expiration rule of one day). This can be created by hand if preferred. If it exists (or can be created) then the template will be uploaded to an object key that is named using the stack and current time in milliseconds.
This doesn't alter the SDK path when the template is smaller than 50kB.
/cc @TBonnin
> Change Riff-Raff to be able to deal with templates over 50kB in size

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/graph/DeploymentGraphTest.scala
- riff-raff/test/deployment/Fixtures.scala
In the frontend application there are a couple of applications that don't exist in CODE (only in PROD). This inconsistency is encoded in the goo tool - but should now be dealt with in the unified deploy.
We neither want to add configuration of stages into the configuration file nor silently fail if no matching ASG is found (a missing ASG might indicate a serious problem). The solution seems to be to have a placeholder ASG with desired size = 0.
Unfortunately Riff-Raff currently fails fast when attempting to deploy an application to an ASG of size zero. This PR modifies the behaviour of a few of the ASG tasks to ensure that this condition is handled gracefully.
See also #244 for previous handling change.
> Modify ASG tasks to succeed when operating on ASGs of size zero

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
This fixes a few problems with #397 and adds some helpful logging for visibility.
1. Make sure that the validate template calls are also included in the "template from URL" party
1. When creating the S3 bucket the lifecycle rule creation needed an ID and a status
1. The template URL needed to be a real `http://` url rather than a `s3://` url
> Cloudformation deployment type fixes

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/input/resolver/TaskResolver.scala
- magenta-lib/src/main/scala/magenta/json/JsonInputFile.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/artifact/S3ArtifactTest.scala
- magenta-lib/src/test/scala/magenta/json/JsonReaderTest.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
Without the delimiter, a listing might include objects from another 'directory' at the same level that happens to share the same prefix.
e.g. Given this bucket layout:
```
`- topLevel
|- subDir
|- subDir2
`- anotherDir
```
Then asking for the contents of `topLevel/subDir` will provide the contents of both `subDir` and `subDir2`. Asking for the contents of `topLevel/subDir/` however will return only the contents of `subDir`.
This PR appends a `/` character in a number of locations such that the listings of artifacts and packages don't unintentionally include files from other artifacts or packages.
> Append delimiter to S3 'directories' so that object listings are accurate

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/artifact/S3ZipArtifact.scala
In #400, I missed a location where a `/` is being explicitly added on an S3 path. This prevents initial deploys that are using the legacy `artifacts.zip` format (prior to them being converted to the new format).
> Correctly construct the path to the legacy artifacts.zip

- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/views/artifact/listFiles.scala.html
- riff-raff/app/views/deploy/viewDeploy.scala.html
- riff-raff/app/views/preview/yaml/preview.scala.html
- riff-raff/app/views/snippets/recordTable.scala.html
- riff-raff/conf/routes
This adds a super simple artifact listing that shows the list of files that are available to riff-raff. This is helpful for debugging why things are not working as expected. It is also possible to download the files directly via Riff-Raff. I don't think this should be a security issue, but it's possible teams are putting secret data in their deployable artifacts.
I've added links to access this from the preview, history and deploy log pages.
Looks like this:
/cc @adamnfish
> Add pages to view and download artifact files

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
Fixing `CheckForStabilization` in #391 has revealed that an ASG can continue to be unstable after a deploy has completed. This happens because the `CullInstancesWithTerminationTag` task is asynchronous and causes an ASG to become unstable again (the ASG desired number < actual number) whilst the ASG kills off the excess instances. 
This state doesn't last for long, but long enough that the `CheckForStabilization` task of a subsequent deploy can fail if it runs immediately after the initial deploy.
This PR introduces a small pause and then a further execution of the `WaitForStabilization` task to wait for the ASG to become stable again. I believe that this should probably only add the pause (default 10s) to most deploys, but might add another 30s if the check doesn't immediately pass.
> Wait again for stabilisation after instance termination

- riff-raff/app/deployment/actors/DeployGroupRunner.scala
This previously relied on there being an always increasing number of child actors. This is not reliable, especially when there are errors. Instead, we use a counter that is internal to the actor (task name is not guaranteed to have only the subset of actor-name-safe characters).
> Ensure that actorNames are really unique

- riff-raff/app/views/preview/yaml/preview.scala.html
- riff-raff/app/views/preview/yaml/showTasks.scala.html
Deploying only one or tow tasks can be quite painful at the moment. This adds buttons that deselect and select all of the tasks in a YAML preview.
> Add buttons to select / deselect all of the tasks

- magenta-lib/src/main/scala/magenta/reporting.scala
- magenta-lib/src/test/scala/magenta/ReportingTest.scala
- riff-raff/app/assets/javascripts/deploy-verbose.coffee
- riff-raff/app/assets/javascripts/report-tree-collapsing.coffee
- riff-raff/app/assets/stylesheets/magenta.less
- riff-raff/app/deployment/model.scala
- riff-raff/app/views/deploy/logContent.scala.html
- riff-raff/app/views/deploy/viewDeploy.scala.html
- riff-raff/app/views/html/helper/magenta/MessageHelper.scala
- riff-raff/app/views/snippets/reportTree.scala.html
- riff-raff/app/views/test/reportTest.scala.html
Large logs are hard to grok at the moment - especially to find the errors. This change makes the logs collapsible and will automatically collapse successfully completed branches. However if a branch fails then it will by default be unfurled making it easy to identify the problems.
In order to do this the `DeployReport` code has been overhauled so as to expose the UUID of each log entry in the tree (in the process a superfluous top level of the tree has been removed and an `EmptyDeployReport` has been introduced). This provides an easy to use ID for targeting in the DOM using the standard bootstrap collapse feature. On top of this there is a little coffeescript that switches out the chevrons when you furl and unfurl part of the tree.
The dotcom deploy is most improved by this. A successful …
> Better logs

- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/controllers/Restrictions.scala
- riff-raff/app/views/deploy/deployHistory.scala.html
A minor fix and an improvement for restrictions.
First up, a bug that @TBonnin mentioned - `\r` characters were not correctly stripped from e-mail addresses in the whitelist meaning it would not correctly match users.
Secondly, it makes sense for users to get feedback early that a deploy will not be possible. A message is now shown to the right of the deploy form when a restriction is in force that matches the project and stage.
> Restrictions improvements

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- riff-raff/app/deployment/actors/TasksRunner.scala
This addresses #413 and should also eliminate the *DeploymentRunner unexpectedly terminated* messages.
The first of these is achieved by modifying the custom retry policy to retry on this one specific `XMLStreamException` (when the message starts with `ParseError at`).
The second is caused by `TasksRunner` actors throwing exceptions. The `DeployGroupRunner` actor watches the child `TasksRunner` actors that it creates so it is notified of unexpected terminations. In this case though the exception is expected and it is communicated back via a message. Unfortunately the exception is re-thrown (for the side effect of sending the appropriate error message to the `DeployReporter`). In order to prevent the Actor terminating we re-catch and blackhole NonFatal exceptions. The Actor will then be …
> Improved exception handling

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- Add a new parameter call amiParametersToTags to handle multiples amiParameters/tags combinations.
- Add tests to ensure that the old amiTags and amiParameter keep having the same behaviour.
**Note**: changes to AmiCloudFormationParameter are really hard to test without a fundamental refactor therefore I plan to test the change in the CODE env.
@sihil @adamnfish @TBonnin @thomaska
> Allow updates to multiple AMI parameters

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormationDeploymentTypeParameters.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- We need sensible defaults for amiParametersToTags for backwards compatibility reasons.
@sihil @adamnfish @TBonnin
> Multiple AMI parameter updates - take2

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
I think most accounts are allowing riffraff user access to all the things e.g. `"cloudformation:*",` but I went for the hard route and discovered all the individual policies for updating an AMI. I thought it might be nice to document the policies similar to `autoscaling` docs.
> Policy required for Riff Raff to update AMI of a stack

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
In the continued quest to vanquish #413 this adds further logging of exceptions that we won't both retrying on (clearly not catching the right thing).
> Add logging in the won't retry case

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/artifact/S3ZipArtifact.scala
- magenta-lib/src/main/scala/magenta/json/JsonInputFile.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/ResolverTest.scala
- magenta-lib/src/test/scala/magenta/json/JsonReaderTest.scala
- project/build.properties
- riff-raff/app/ci/CIBuild.scala
- riff-raff/app/ci/S3Build.scala
- riff-raff/app/ci/S3Tag.scala
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/preview.scala
- riff-raff/app/deployment/preview/PreviewCoordinator.scala
Reverts guardian/riff-raff#426
It was noticed this morning that autocomplete and continuous deployment (frontend for example) ceases to function. Restarting riff-raff didn't fix the issues, however deploying the previous version (#662) brought back autocompletion.
Reverting this PR since it could be the cause of the problems.
> Revert "Exceptions => Error values"

- project/Dependencies.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/resources/PrismLookup.scala
- riff-raff/test/lookup/PrismLookupTest.scala
Whilst looking at something with @thomaska we noticed that the query to Prism did not use the region that is provided to the `getLatestAmi` call. This has worked as we are only in one region, but will cause confusion when that is no longer the case.
This provides a fix along with a few tests to describe the behaviour.
> Ensure region is used to filter images from prism

- build.sbt
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/ElasticSearchTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- project/Dependencies.scala
- riff-raff/app/conf/context.scala
Also fixes all deprecation warnings. (Mostly how the different aws clients are being constructed)
`1.11.106` contains the fix to the `XMLStreamExceptions` issue we have been trying to fixed for a while now. See https://github.com/guardian/riff-raff/issues/413 and https://github.com/guardian/riff-raff/pull/415
https://github.com/aws/aws-sdk-java/blob/799319f670344153d588e7e42095653fabf01673/CHANGELOG.md#bugfixes
> Update AWS SDK to 1.11.106

- riff-raff/app/lifecycle/ShutdownWhenInactive.scala
Would log something like this:
`RiffRaff not yet inactive ('ophan::Data Lake::ophan-event-stream-etl 1413' is still running), deferring shutdown request`
> Log running builds when riff-raff shutdown is deferred

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
We saw a deploy that threw an NPE on this line. Aside from the `logger` the only expression that looked like it might throw an NPE is the `originalRequest` so this guards it in an option in the log expression.
> Wrap request so we don't NPE when it is null

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Param.scala
- magenta-lib/src/main/scala/magenta/deployment_type/SelfDeploy.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/assets/stylesheets/magenta.less
- riff-raff/app/conf/context.scala
- riff-raff/app/deployment/DeploymentEngine.scala
- riff-raff/app/deployment/Deployments.scala
- riff-raff/app/deployment/LegacyPreview.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/filter.scala
- riff-raff/app/deployment/model.scala
- riff-raff/app/persistence/DynamoRepository.scala
- riff-raff/app/persistence/mapping.scala
- riff-raff/app/persistence/mongodb.scala
- riff-raff/app/persistence/package.scala
- riff-raff/app/persistence/representation.scala
- riff-raff/app/views/snippets/recordTable.scala.html
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
It's time to officially deprecate `deploy.json`!
A lot of people have already migrated and it is well testing. I've already created plenty of carrot with entertaining tech times, documentation and the validation tool - so now I'm suggesting a light touch stick. 
To that end I've:
- added highlighting of deploys using deprecated features to the history screen (see below)
- built functionality that will pause for an increasing number of seconds when deploys use `artifact.zip` or `deploy.json` (this will be 0 seconds until the 23rd of May and form then on will increase by 1 second per calendar day)
I've set an explicit end of Sept 2017 date at which point we can start massively simplifying the codebase and mention this in the deprecation warnings.
I'll send some comms out around this …
> Deprecate deploy.json and add pauses as a forcing function for migration

- riff-raff/app/assets/stylesheets/magenta.less
- riff-raff/app/views/snippets/recordTable.scala.html
Adds a little badge to the status column to make the warning highlighting clearer.
> Add an explicit warning badge to make it clearer

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Param.scala
We shouldn't have defaults for things that appear to be magical / surprising. This deprecates another example where this is currently a little too magical: the fileName of a lambda.
By deprecating it we don't break deploys but we do pave the way to best practices.
> Deprecate another default

- magenta-lib/src/main/scala/magenta/graph/Graph.scala
- magenta-lib/src/test/scala/magenta/graph/GraphTest.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/test/deployment/Fixtures.scala
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
I believe this fixes #438. The new DeployGroupRunner test definitely produced the tell tale `DeployUnfinished` logging before the changes were made.
> Only consider reachable nodes when determining deployment completion

- riff-raff/app/conf/context.scala
Attempting to call `Period.toStandardDays` on a period longer than month causes `UnsupportedOperationException: Cannot convert to Days as this period contains months and months vary in length`.
`Days.daysBetween` doesn't have this limitation. 
This is already deployed as everything was blowing up.
> Don't blow up if more than a month since deprecation date

- riff-raff/app/controllers/Application.scala
- riff-raff/app/views/deploy/logSummary.scala.html
- riff-raff/public/docs/howto/fix-a-failed-deploy.md
This adds a link to the fix a failed deploy documentation to the Documentation menu and the deployment page when it fails. And also only has one method to shrink an ASG. 
This is so (hopefully) when your deploy fails (hopefully not) the remediation pathway is just _there_ as a helpful reminder. Useful if you're not quite sure what the really long aws command needed is. (Especially if it's 3am on 247)
note: needs testing on CODE
> Fix a failed deploy

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
If `riffraff.yaml` is misconfigured or similar, we should provide some diagnostic information, so that it can be easily corrected.
Originally, I had made this an error, but figured it's possible that it's legitimate in some case, so backed down to a warning.
> Warn if we're attempting to upload 0 files

- magenta-lib/src/main/scala/magenta/artifact/S3ZipArtifact.scala
By default `Files.copy` throws an exception if you try to copy over an existing file. In this case, we've just created a temp file, so it's safe to overwrite it and passing the appropriate `CopyOption` allows this to happen successfully.
> Fix old, zipped deploys

- riff-raff/public/docs/riffraff/administration/auth.md
- riff-raff/public/docs/riffraff/administration/move.md
@philwills  Some docs about this mornings host swap for you.
Also: what do we think about changing output of `management/switchboard` to plain text to make it easier to parse curl output?
> Some documentation for when riffraff needs to be moved between hosts.

- build.sbt
Riff-Raff was using the default JVM options - this improves the situation significantly by adding some sensible memory allocation as well as fixing the old RUNNING_PID file issue.
> Add some better JVM options

- riff-raff/app/AppComponents.scala
- riff-raff/app/AppLoader.scala
- riff-raff/app/ci/CIBuild.scala
- riff-raff/app/ci/ContinuousDeployment.scala
- riff-raff/app/ci/TargetResolver.scala
- riff-raff/app/controllers/TargetController.scala
- riff-raff/app/persistence/TargetDynamoRepository.scala
- riff-raff/app/views/deployTarget/deployButton.scala.html
- riff-raff/app/views/deployTarget/noMatchForTarget.scala.html
- riff-raff/app/views/deployTarget/selectTarget.scala.html
- riff-raff/app/views/deployTarget/selectVersion.scala.html
- riff-raff/app/views/snippets/recordTable.scala.html
- riff-raff/conf/routes
If you are armed with the region, stack, stage and app (RSSA) of an instance (say from AMIable telling you an AMI is out of date) then this provides a mechanism for locating the appropriate deploy.
There are two parts. 
1. A target resolver that
- watches for new builds
- resolves the deployment graph for each new build to figure out the SSA that it targets and stores the results in a dynamo table
2. a little frontend that
- takes a RSSA
- looks it up in the dynamo table
- guides the user in selecting the best fit
The RSSA might be ambiguous, if so the user will be shown the options (this is ambiguous because of an error in a file):
Next, the most recent deploys are shown and the user is asked which should be redeployed:
Finally, the confirmation screen that we all know and love:
This …
> Add deploy mechanism when you know region, stack, stage and app

- riff-raff/app/assets/javascripts/notifications.coffee
At the moment, we're liable to see notifications that end in "has f..." which is horribly ambiguous.
Open to other suggestions on how to fix this.
> Add helpful emoji to the deployment notifications.

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
A couple of improvement to CFN updates I noticed whilst working on some AMI updates.
1. If the update fails and rolls back is doesn't always report a FAILED status. Think that it should also fail if any status is seen with ROLLBACK in.
2. If something else is currently updating the stack we should wait and try again shortly. This uses similar logic to the check, but focused around retrying.
We usually don't retry during deploys and instead fail fast. I think it makes sense to retry here as the locking is being dealt with elsewhere so we don't need to concern ourselves with it.
The use case is where a project has individual builds/deploys going to multiple ASGs in a single CFN stack. Each deployable is configured to update a parameter that controls the AMI for the instances it controls. It …
> Cloudformation update improvements

- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
The 'package' name is essentially the deployment name (the key under deployments in riff-raff.yaml). The 'app' name is the same by default but can be overridden using the app key in a deployment or template.
When we generate the S3 key for uploading and updating a lambda, by using the app name instead of package name then it becomes possible to override the value, which in turns allows the lambda upload and update tasks to be split (so it can be put either side of a CFN update).
I've gone through all of the existing riff-raff.yamls that use the aws-lambda deployment type and confirmed that there will be no change of behaviour for any existing configurations.
> For lambda: when building the S3 key, use the app instead of pkg name

- magenta-lib/src/main/scala/magenta/artifact/S3Location.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
There have been very few deploys that rely on the old formats in the last month. This fulfils the statement in the deprecation messages that support would be removed at the end of September.
> Disable support for artifact.zip / deploy.json

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- readme.md
If dependancies for certain deployment types are not stated in `riff-raff.yaml`, a race condition will be introduced that writes over the desiredSize for the ASG - causing the deploy to fail. This PR adds more detail to the docs and the error to give more clarity.
[Example failed deploy](https://riffraff.gutools.co.uk/deployment/view/684e0b13-3588-418e-8189-731fc276b381)
> Add more troubleshooting detail for when deploys fail due to dependancy clash

- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
The equivalent of setting `--sse aws:kms` on S3 uploads, meaning objects are encrypted using per-account [Amazon managed keys](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html). The keys are created automatically on demand.
For reference, you can mandate all uploads to a bucket are encrypted this way with policy:
```yaml
EnforceDistributionBucketEncryptionPolicy:
Type: AWS::S3::BucketPolicy
Properties:
Bucket: !Ref DistributionBucket
PolicyDocument:
Id: EnforceDistributionBucketEncryptionPolicy
Statement:
- Effect: Deny
Principal: "*"
Action: s3:PutObject
Resource: !Sub "arn:aws:s3:::${DistributionBucket}/*"
Condition:
StringNotEquals:
"s3:x-amz-server-side-encryption": "aws:kms"
- Effect: Deny
Principal: "*"
Action: s3:PutObject
Resource: !Sub …
```
> Use automatic S3 encryption when uploading

- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
Revert #470 to unblock Frontend deploys whilst we investigate why they broke
> Revert "Use automatic S3 encryption when uploading"

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
Riff-raff currently executes a initial single check to verify the ASG and ELB have the same number of instances.
In case the ASG is currently scaling up/down when ASG deploy is being started, the check fails and the deploy is terminated.
From now on Riff-raff will wait for the ASG to stabilize (for a short
period of time) before to fail the deploy rather than making a single check.
It shouldn't impact the deployment speed if the ASG is already in a stabilised state but it will help apps like frontend when scaling events happen on a regular basis during the day.
I picked `1 minutes` as the initial timeout so riff-raff doesn't wait to much in case something is wrong but still give a chance to the ASG to finally stabilised. Let me know what you think @sihil
> Autoscaling: wait for stabilization rather than initial single check

- magenta-lib/src/main/scala/magenta/Project.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
@marialivia16 and I have figured out that the Riff-Raff cloud formation task can mistakenly believe that a stack doesn't exist if it happens to be on the second page of results from the API (which we don't check when we look it up by name).
The simple solution is to specify the name in the request so that the result set is not greater than one result. 
We also added some verbose logging of the assembled key rings that we used whilst debugging and think will be useful in other situations.
> Fix Cloud Formation task when an account has over 100 stacks

- riff-raff/app/controllers/ScheduleController.scala
- riff-raff/app/schedule/DeployScheduler.scala
- riff-raff/app/views/schedule/list.scala.html
This switches to the normal logger, renames the unschedule method and also sorts scheduled jobs by project and then stage (should this really sort by schedule expression to allow people to space out the schedule???)
> Tidy up implementation and sort scheduled jobs listing

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
We recently moved an internal project to a blue/green deployment model using a EC2 [Application Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html) to switch between stages.
I found that I needed some additional IAM permissions to get the deploys to work with the new balancers. The AWS console also says that `elb:DescribeInstanceHealth` is unrecognised so I have removed it.
> Update permissions required for an ASG deploy

- magenta-lib/src/main/scala/magenta/Lookup.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormationDeploymentTypeParameters.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- magenta-lib/src/test/scala/magenta/fixtures/package.scala
- riff-raff/app/resources/PrismLookup.scala
- riff-raff/test/lookup/PrismLookupTest.scala
With https://github.com/guardian/amigo/pull/164 it has become necessary to add a little more functionality to Riff-Raff to correctly identify a suitable AMI (encrypted AMIs must be in the same account as they are used). A new boolean parameter `amiEncrypted` has been introduced to support this.
Most importantly we don't want Riff-Raff to inadvertently pick up an encrypted AMI when one had not been requested. If it tried to do this and picked an AMI from a different account it would not work. At all. As such, when `amiEncrypted=false` (the default) we only consider AMIs that either have no `Encrypted` tag or those that have an `Encrypted=false` tag.
When we set `amiEncrypted=true` Riff-Raff does two things:
- only considers owned by the AWS account ID belonging to the AWS credentials being …
> Add support for AMIgo based encrypted AMIs

- riff-raff/app/controllers/api.scala
I want to ingest this into a Kibana stack we have so that we can track our deploy times over time.
**Note: not yet tested other than it compiles.**
> Expose build duration in seconds

- riff-raff/app/ci/S3Build.scala
- riff-raff/app/utils/Json.scala
We've seen a `build.json` with a badly formatted date. This should deal more gracefully with that and provide logging to track down the offending file.
> Deal with invalid date time format and log build.json parsing errors

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
This change makes riffraff check that all ELBs in a stack are healthy.
This also fixes an issue where a stack with both classic and V2 ELBs fails to deploy.
> Check status of multiple classic and V2 ELBs

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
We no longer convert to json, as AWS supports this now.
@sihil
> Update docs for cloudformation deploy

- project/Dependencies.scala
- project/plugins.sbt
- riff-raff/app/AppComponents.scala
- riff-raff/app/conf/context.scala
- riff-raff/conf/application.conf
The Play Application Secret is used to sign the `PLAY_SESSION` cookie:
https://www.playframework.com/documentation/2.6.x/ApplicationSecret
Any attacker possessing the Play Application Secret can easily craft a signed `PLAY_SESSION` cookie masquerading as any legitimate user they desire. Assuming network access to Riff-Raff, they can then deploy any version of any app with the elevated privileges of that user.
This change updates Riff-Raff to use the our new library for rotating Play secrets without downtime: https://github.com/guardian/play-secret-rotation
The cloudformation for the Guardian's instance of Riff-Raff isn't in this repository, but an update to the EC2 instance IAM policy is also required, adding AWS Parameter Store and KMS permissions as defined in: …
> Make it easy to rotate the Play Application Secret

- build.sbt
- magenta-lib/src/test/scala/magenta/deployment_type/ParamTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentResolverTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/AppLoader.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/controllers/TargetController.scala
- riff-raff/app/controllers/Testing.scala
- riff-raff/app/controllers/api.scala
- riff-raff/app/controllers/authentication.scala
- riff-raff/app/deployment/Deployments.scala
- riff-raff/app/housekeeping/ArtifactHousekeeping.scala
- riff-raff/app/persistence/mapping.scala
- riff-raff/app/persistence/mongodb.scala
- riff-raff/app/schedule/DeployJob.scala
- riff-raff/app/utils/LogAndSquashBehaviour.scala
- riff-raff/conf/routes
- riff-raff/test/housekeeping/ArtifactHousekeepingTest.scala
The aim of this PR is to delete old and unused Riff-Raff artifacts.
The strategy is:
- list all of the project names in the root of the S3 bucket
- for each project name
- find builds we should keep:
- query the riff-raff DB for the last 50 successful deploys of that project
- find the most recent 5 for each stage in the results
- make a list of builds to keep by combining the list above
- tag builds that we don't want to keep:
- get a complete list of all builds in the bucket
- compute `allBuilds - buildsToKeep`
- tag all objects under each `${project}/${buildId}` prefix
- Modify the lifecycle policy on the artifact bucket to remove files that are older than 40 days **_AND_** tagged
TODO
------
> Remove old riff-raff artifacts that are not used

- riff-raff/app/housekeeping/ArtifactHousekeeping.scala
Optional since maybe we do want to tag everything for deletion if a project has never been deployed?  
However, just in case the check on the builds to keep list returns an empty list rather than an error, maybe we want to skip tagging of it for now?
This did manage to happen on PROD last night:
`h.ArtifactHousekeeping - Keeping 0 builds of <projectName> (List())`
Discuss! 
..Either way, this probably needs to get merged and deployed to PROD before tonight 😈 🔥 🔥
> Skip tagging if the list of builds to keep is an empty list

- build.sbt
Another repo that needs to be updated in order to compile now HTTP has been switched off.
> Switch the Guardian github repo to HTTPS

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
CAPABILITY_NAMED_IAM is a strictly more powerful than CAPABILITY_IAM. That extra power is something we need occasionally but it is fine to always pass it.
> Use more powerful IAM capability for CF updates

- riff-raff/app/ci/ContinuousDeploymentConfig.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/persistence/datastore.scala
- riff-raff/app/persistence/mongodb.scala
- riff-raff/test/RepresentationTest.scala
The related collections have been dropped in MongoDB. I have move the declarations for `NoOpDataStore` because as we start writing a `DataStore` for Postgres, it will be nice if the compiler lets us know if something is missing.
> Cleanup some MongoDB code before the big move

- contrib/riff-raff-yaml-schema.json
- magenta-lib/src/main/scala/magenta/input/package.scala
IntelliJ and other editors have sprouted support for validating YAML files with JSON schema. This is a schema file that can be referred to in JSON or YAML using `$schema` (although IntelliJ doesn't yet appear to automagically pick this up when it's YAML).
As well as the schema file we modify Riff-Raff to ignore properties that start with a `$` character to allow the `$schema` and `$id` fields to be specified if so desired.
> Create a simple JSON schema definition for riff-raff.yaml

- riff-raff/app/controllers/authentication.scala
This should redirect people from login to the main index on successful login and also redirect people who failed to login back to the login screen and display the error.
> Switch the redirect targets to fix behaviour

- riff-raff/app/persistence/mapping.scala
- riff-raff/app/persistence/package.scala
- riff-raff/test/RepresentationTest.scala
I've noticed a number of duplicated log lines which are causing chaos in the log viewer. I suspect that this is down to our policy of trying Mongo updates repeatedly if we get an error, meaning that we ensure that a log line is successfully written at the cost of introducing duplicates in the case that it has written successfully but still threw an error.
The proper fix is to switch from inserts to upserts to ensure that any deduplication happens in the DB. However this can't be done until duplicates have already been removed so this is a short term kludge to fix the immediate problem by filtering out duplicates on read.
> De-duplicate log entries when reading from the DB

- riff-raff/app/conf/context.scala
We've changed the way we read config and in the process we managed to make any list property required, resulting in continuous deployment being broken. This fixes it by defaulting to an empty list when a list property is missing from the config file.
> Consider optional lists in configuration

- riff-raff/app/AppComponents.scala
- riff-raff/app/notification/hooks.scala
- riff-raff/app/schedule/DeployJob.scala
- riff-raff/app/schedule/DeployScheduler.scala
During the config refactoring we broke the way we were sending params to the job when scheduling deployments. This should fix it.
> Fix scheduled deployment

- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/deployment/filter.scala
- riff-raff/app/persistence/package.scala
- riff-raff/test/postgres/PostgresDatastoreTest.scala
We introduced a regression when merging the Postgres API regarding searching for projects on the history page. We should be able to search for a substring of the project name. I've also added a test in postgres for it.
> Fix search by project name

- project/Dependencies.scala
- riff-raff/app/controllers/MigrationController.scala
- riff-raff/app/migration/Migration.scala
- riff-raff/app/migration/Migrator.scala
- riff-raff/app/migration/data/MongoRetriever.scala
- riff-raff/app/migration/data/ToPostgres.scala
- riff-raff/app/migration/data/package.scala
- riff-raff/app/migration/dsl/interpreters/MigrateInterpreter.scala
- riff-raff/app/migration/dsl/interpreters/Postgre.scala
- riff-raff/app/migration/dsl/interpreters/PreviewInterpreter.scala
- riff-raff/app/persistence/mapping.scala
- riff-raff/app/persistence/mongodb.scala
- riff-raff/app/views/migrations/preview.scala.html
The most important change is that the mongo queries were running on a yielding thread pool, which is bounded by the number of CPUs. They now run on an unbounded pool suited for synchronous, blocking IO.
> Few changes to migration

- riff-raff/app/conf/context.scala
- riff-raff/app/persistence/datastore.scala
- riff-raff/app/utils/ScheduledAgent.scala
Following the config migration we were instantiating one metrics object per postgres request 😱
> Instantiate the metrics scheduler only once

- riff-raff/conf/evolutions/default/3.sql
Currently we have some slow queries as they are taking place on the startTime field as a TIMESTAMP value. Currently we only have an index for startTime as a TEXT value. This rectifies that, following suggestion here https://stackoverflow.com/questions/29757374/create-timestamp-index-from-json-on-postgresql#comment47648833_29757374 
https://github.com/guardian/riff-raff/pull/533 modifies the app to start using the new function this evolution adds.
> Add index for startTime with timestamp conversion.

- riff-raff/app/AppComponents.scala
- riff-raff/app/ci/ContinuousDeployment.scala
- riff-raff/app/notification/DeployFailureNotifications.scala
Ronseal.
We had an issue in Ed Tools that would have been caught sooner had we noticed that a deploy triggered from a GitHub merge had failed.
> Notify when both continuous and scheduled deployment fail

- project/Dependencies.scala
Sadly this forced upgrade broke fastly deploys, so gonna have to remove it for now and bring back the vulnerability.
Hopefully when this is release https://github.com/guardian/fastly-api-client/pull/19 we can import it and the problem will be solved.
> Remove forced ning upgrade

- project/Dependencies.scala
...to pull in [ning http upgrade](https://github.com/guardian/fastly-api-client/pull/19) which patches a vulnerability.
> Bump fastly api client to version 0.2.7.

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
Clouformation deploys involving a large template are currently broken due to the recent [upgrade of the AWS sdk](https://github.com/guardian/riff-raff/pull/545) in riffraff. This fixes the problem. I couldn't find a method in the new sdk for generating a url given a bucket and key so I've manually constructed it here.
Example failed deploy: https://riffraff.code.dev-gutools.co.uk/deployment/view/84fe9dd4-3182-4d38-9226-edf97512c9f5
> Fix large cloudformation deploys

- riff-raff/app/deployment/Deployments.scala
This might resolve one race condition that results in Riff-Raff thinking that a deploy has not finished when it has in fact completely failed to start.
In a recent example, both of the phantom deploys were triggered as scheduled deploys but had throw an exception which indicated that it has not yet arrived in the deployments Agent prior to being accessed.
The following exception was being thrown:
```
java.util.NoSuchElementException: key not found: 8d2d899a-875b-4824-87bc-7eb03437ac75
<snip>
at deployment.Deployments.await(Deployments.scala:223)
at deployment.Deployments.create(Deployments.scala:69)
at deployment.Deployments.$anonfun$deploy$5(Deployments.scala:47)
<snip>
```
The following code was blowing up on the `create` call. The call was registering the new deploy and then calling …
> Attempt to fix a race condition that leads to Riff-Raff not deploying

- project/Dependencies.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/AppLoader.scala
- riff-raff/app/conf/context.scala
- riff-raff/conf/application.conf
For great security gains! Essentially AWS RDS allows you to generate a password for a database user via IAM if that user has the rds iam role assigned to it in postgres. This PR includes the changes that need to be made to the app in order for it to fetch this password and use it. There's some complexity because we're using Play to handle our database evolutions, and the only way to configure play evolutions is using properties in the application context config - so having fetched the password from RDS we're having to use it to set the db.default.password property in the ApplicationLoader. 
Before this is merged:
> [WIP] Add functionality to fetch db password via RDS IAM.

- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
A phoenix of #499.
Making a deployment generic enough to run across several stages or stacks is currently difficult and requires a high level of discipline with the naming of functions. For example it is currently necessary to hardcode the function name in the cloudformation rather than use dynamically generated names.
This PR allows lambdas to be targeted based on the set of tags that they have. This is similar to the way that autoscaling groups are discovered in `autoscaling` deploys.
This allows a more general approach to deployment. https://github.com/guardian/cloudwatch-logs-management is a good example of where this is helpful: a stack that can be deployed to multiple AWS accounts in which the function names are not specified.
The code follows the same pattern used for …
> Target lambda deployments using tags

- riff-raff/app/persistence/postgresdb.scala
Currently we are getting authentication errors as a result of riffraff trying to authenticate with RDS using an expires IAM token as connections are dropped/re opened. this is a stopgap fix to attempt to solve the issue before we can do something more thorough. The theory is that if we have initialSize and maxSize of the connection poolthe same then the app will maintain a consistent number of open connections. @alexduf  pointed out that this won't solve a case where a connection is dropped due to network issues, so we need a more permanent solution eventually
> Attempt to set postgres connection pool to a fixed size.

- riff-raff/app/AppComponents.scala
- riff-raff/app/AppLoader.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/persistence/DynamicPasswordDataSourceConnectionPool.scala
- riff-raff/app/persistence/IAMPasswordProvider.scala
- riff-raff/app/persistence/postgresdb.scala
- riff-raff/test/postgres/PostgresHelpers.scala
We currently provide a fixed pool to access our database. IAM provide passwords that are valid for 15 minutes, which means any connection dropped after that mark can't and won't be replaced.
We shouldn't rely on the network being reliable, this mean if some connection gets dropped, the number of active connection to the DB will slowly decrease until it's depleted.
I'm providing a connection pool, with a special `ConnectionFactory`. The connection factory is invoked every time a fresh connection is attempted. This gives us an opportunity window to go to IAM and request a new password.
- The call to IAM is blocking, this will impact the application performance, but it should work. This is alleviated by adding a 12 minute cache on the validity of the password.
- The cache doesn't attempt to …
> Provide a way to create connections with a dynamic password.

- build.sbt
- project/plugins.sbt
- riff-raff/app/views/deploy/dashboard.scala.html
- riff-raff/app/views/deploy/history.scala.html
- riff-raff/app/views/page.scala.html
- riff-raff/app/views/preview/yaml/loading.scala.html
- riff-raff/app/views/snippets/changeFreezeDialog.scala.html
- riff-raff/conf/routes
when testing https://github.com/guardian/riff-raff/pull/556 in CODE, it required busting the browser-cache to see the changes fully take effect (old javascript was being loaded).
This PR implements [`Assets.versioned`](https://www.playframework.com/documentation/2.7.x/AssetsOverview#Reverse-routing-and-fingerprinting-for-public-assets) via [sbt-digest](https://github.com/sbt/sbt-digest#sbt-digest). So now assets are prefixed with a hash to ensure changes get reloaded properly...
> add 'sbt-web' 'digest' plugin and switched to Assets.versioned

- riff-raff/app/assets/javascripts/form-autocomplete.coffee
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/deployment/filter.scala
- riff-raff/app/views/deploy/deployHistory.scala.html
- riff-raff/app/views/deploy/form.scala.html
- riff-raff/app/views/snippets/recordTable.scala.html
- riff-raff/conf/routes
On the deploy screen, the small deploy history table on the right doesn't display the project name and yet the project name filter WAS a wildcard search `like  %$pn%` which meant clicking on projects like `identity` would produce a very confusing/alarming list containing builds from multiple projects (often with very different build numbers).
NOW its an exact match search on the deploy screen...
... feature co-authored with @TBonnin 
PLUS @philmcmahon suggested adding some sort of link to those historical deploys (from that small history table on the deploy screen), so made sense to do it at the same time...
... the entire row is clickable but opens in a new tab when on the deploy screen.
> make project field exact match on deploy screen PLUS pop-out link on same mini history table

- project/Dependencies.scala
Currently when we try to deploy Fastly deploy configurations that have VCL files beyond a certain length (I tested with 100,000 characters) the deploy fails. The latest version of fastly api client should resolve this issue, by posting data to the fastly api in a more sensible way - here's the PR https://github.com/guardian/fastly-api-client
VCL deploys are broken on CODE so I've tested this as much as possible (I ran an autoscaling deploy on CODE)
> Bump fastly api client to version 0.3.0 to fix large Fastly VCL deploys.

- project/Dependencies.scala
Following from https://github.com/guardian/fastly-api-client/pull/21 - which modifies the client so that it always url encodes vcl being uploaded - a requirement of the fastly api.
> Bump fastly client to 0.4.0

- magenta-lib/src/main/scala/magenta/package.scala
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/ElasticSearchTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
An alternative to #561.
Best reviewed with whitespace edits disabled.
> Ensure that AWS SDK objects are closed after use

- magenta-lib/src/main/scala/magenta/deployment_type/BucketParameters.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- project/Dependencies.scala
NOTE: this is built on top of #547 and should be merged _after_ that
An alternative approach to #549 which avoids creating buckets automatically and is more aligned to existing behaviour.
This is an implementation of an idea that @philmcmahon and I were throwing around to solve the scenario in which you want to deploy a stack to multiple accounts easily. There are two main approaches:
- put the artifact into a shared bucket and point multiple instances/lambdas across the multiple accounts to the same shared bucket 
- have one artifact bucket per account and point each instance/lambda at the local bucket
The second of these is preferable for a few reasons (avoidance of cross account permissions primarily) but it is not possible to create two buckets with the same name in different …
> Add option to lookup bucket from an SSM key in the target account

- riff-raff/app/AppComponents.scala
- riff-raff/app/AppLoader.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/controllers/Testing.scala
- riff-raff/app/views/menu/menubar.scala.html
- riff-raff/app/views/page.scala.html
- riff-raff/app/views/test/running.scala.html
- riff-raff/conf/routes
- riff-raff/test/ci/S3BuildTest.scala
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
- riff-raff/test/lookup/PrismLookupTest.scala
- riff-raff/test/postgres/PostgresHelpers.scala
Riff-Raff occassionally doesn't restart on deploy which is hard to detect at the moment. This PR adds the start time of the VM to the bottom of the UI so it's trivial to diagnose. It also adds a new `/testing/running` endpoint that lists the deploys that the internal deploy controller believes are still running. Again this might make it easier to diagnose why Riff-Raff failed to shut down.
> Helpful things for DevX

- riff-raff/app/views/page.scala.html
provide a better experience for clients that don't support prefers-color-scheme
load usual css always and conditionally load dark mode if `prefers-color-scheme` is supported and you've specified a preference for dark mode
> provide a better experience for clients that don't support prefers-color-scheme

- riff-raff/app/assets/stylesheets/magenta.less
when dark mode, text is black to provide more contrast between text and background
**before**
**after**
> add more contrast to history hover

- riff-raff/app/AppComponents.scala
- riff-raff/app/notification/DeployFailureNotifications.scala
Some projects have lots of different stack names so it's easier to identify an owner using the AWS account id. This change adds 'aws account id' to the list of 'targets' that riffraff sends to [anghammarad](https://github.com/guardian/anghammarad) after a deploy failure, so that this value can be used to determine the project owner.
> Add AWS account ID as Anghammarad target.

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/conf/Secrets.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/resources/PrismLookup.scala
- riff-raff/test/lookup/PrismLookupTest.scala
This changes the way credentials are built to source them from SSM param store instead of a config file in S3. At a later point we might migrate the whole config to SSM param store but this is the most important bit.
I initially wrote this to support both the config file and SSM but that just added compexity for no reason. I also initially wrote this so that keyrings were built from live data in AWS. I switched to fetch credentials at startup to make it more robust. It could be changed to have a refresh endpoint if so desired.
I've imported credentials for CODE and PROD as of 9am on the 13th Feb and the build is currently on CODE and tested as working.
There are currently no credentials for DEV. When there are, they will at least no longer be on a developers machine, although they will be …
> Source credentials from SSM

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
It sometimes makes sense that a cloudformation template needs the current build ID when being updated by Riff-Raff. This provides that data when there is a `BuildId` parameter in a CFN template.
I also updated the docs to actually document this feature.
There is a small risk that we'll start to clobber `BuildId` if this is a parameter on a template that is currently deployed by Riff-Raff. I suspect this is unlikely.
> Make the build ID available as a RiffRaffBuildId parameter

- .sbtopts
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/controllers/PreviewController.scala
- riff-raff/app/controllers/api.scala
- riff-raff/app/controllers/authentication.scala
- riff-raff/app/views/errorContent.scala.html
- riff-raff/app/views/validation/validationErrors.scala.html
Preview can fail in a couple of different ways, one of which is a deployment graph that can't be built because of a validation error and the other is an exception being thrown somewhere during the preview. I've improved both. 
For the validation error case it was doubling the furniture in a weird way so I've removed the `@main` wrapper around the response. 
In the latter case the refresh endpoint was blowing up with a 500 which the autorefresh script was ignoring. I've added a `recover` clause that deals with the future throwing an exception and simply displays that exception.
As a bonus I added an `.sbtopts` file that sets sensible memory values for SBT so it doesn't blow up all the time.
> Fix preview display when the preview value is a failed future

- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
This narrows the guard for the good empty change set condition to only be when there is a status reason indicating there are no updates. Without this bad templates were passing this step and it looked like a cloudformation update had completed.
> When we are creating we are interested in failures with empty change sets

- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
Reverts guardian/riff-raff#576.
It seems like the logic is missing some messages like `The submitted information didn't contain changes. Submit different information to create a change set.`. Reverting while we investigate
> Revert "Unless it is no-op we are interested in failures with empty change sets"

- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
Second attempt at #576 where we distinguish between the conditions of failed empty change sets so that we allow no-op changes to succeed whilst also failing fast for garbage templates.
> Fail fast when applying garbage template

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
This PR lays the groundwork for a logic change to fix a long standing corner case where a default parameter in a CloudFormation template takes priority over a manually set value in a live CloudFormation stack.
There are no intentional functional changes in this PR - it is designed to restructure the code to make it easier to test and reason about ahead of fixing the bug in question. 
Some notable changes:
- Switch most things from `Seq`/`Iterable` to `List` for consistency
- Move logic out of a class and into the companion object
- Move calls to AWS outside the main logic
- Move the reporter failure call outside main logic so we don't deliberately throw exceptions
- Pass through the list of existing parameters from the live stack - this is not used but is required to fix this bug so will …
> Restructure CloudFormation param logic

- riff-raff/app/controllers/authentication.scala
Introducing this as I've recently had to troubleshoot access that didnt' work due to a trailing space on the address that was added.
> Trim email address when user added

- riff-raff/app/controllers/DeployController.scala
If the project name contains URL-encoded characters (for example spaces) it returns a `key not found` error when you try to download an artifact.
For example in the artifacts page for a [Editorial Tools::Flexible Content](https://riffraff.gutools.co.uk/deployment/request/deployFiles?projectName=Editorial+Tools%3A%3AFlexible+Content&id=8712) deploy, the links to the `.deb` files have the space in the project name encoded as `%20`:
```
https://riffraff.gutools.co.uk/deployment/request/artifactFile/Editorial%20Tools::Flexible%20Content/8712/composer-backend/composer-backend.deb
```
but when you follow that link, Riff-Raff throws an error:
```
software.amazon.awssdk.services.s3.model.NoSuchKeyException: The specified key does not exist. (Service: S3, Status Code: 404, Request ID: …
```
> URL decode the key to download to work with spaces in the project name

- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
This PR changes the logic that resolves the set of parameters to use when creating a CloudFormation change set. It fixes a long standing bug where a default value for a parameter in the template took priority over a live value in the CloudFormation stack.
Note that this PR cannot be merged until #579 as it builds on restructuring that was introduced there.
This is a relatively risky change so it would be good to have a couple of pairs of eyes on it.
> Change param logic to stop default template values overriding live stack values

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
There was a corner case where it wasn't possible to deploy when a parameter was removed from a template due to the change introduced by #580.
This is a relatively small change that only reapplies existing parameter values when the parameter exists in the template.
> Should be possible to remove existing parameters from a stack

- riff-raff/app/controllers/TargetController.scala
Use the exact projectName when filtering for recent deploys, we've already retrieved an entry from the dynamo repository (in the lines before this) so we can use the exact projectName rather than regex it as we've validated it exists.
`DeployFilter(Some(^editorial-tools:remote-machines$),None,Some(PROD),None,None,None,None)`
`DeployFilter(Some(editorial-tools:remote-machines),None,Some(PROD),None,None,None,None)`
Related to https://github.com/guardian/amiable/pull/55.
> adjust filter in TargetController

- readme.md
- sbt-debug
- script/start
Running `./script/start --debug` will allow you to attach a remote debugger on port 9999.
An alternative to this would be to have a `./script/debug` script instead - thoughts welcome!
> add --debug flag to make interactive debugging easier

- riff-raff/app/housekeeping/ArtifactHousekeeping.scala
Riffraff was not deleting old deploys in S3 (see this [issue on the DevX trello board](https://trello.com/c/XVO7tSSt)), so our S3 storage has been gradually climbing. See this chart below:
We realised that the DeployFunction was doing a fuzzy match on the app name. The SQL looked like this, for example: `'%^Apps::iOS::master-debug$%'` which is invalid for a [`LIKE` fuzzy match](https://www.postgresql.org/docs/8.3/functions-matching.html) as the `^` and `$` aren't supported. Therefore, the function wasn't capturing any deploys to delete.
To do an exact match we needed to remove the `%` characters, which is provided by the `isExactMatchProjectName` property. We changed this so that the SQL became `'Apps::iOS::master-debug'` and we added a parameter to get the exact project name.
> Fix DeployFilter for housekeeping query

- riff-raff/app/conf/context.scala
Sets a region on the STS client. Suspect it works in TeamCity as it can figure it out from the instance but doesn't run locally.
> Fix tests so they run locally

- riff-raff/public/docs/howto/configure-a-project.md
- riff-raff/public/docs/reference/build.json.md
Tiny documentation change: while browsing the docs I noticed that these link to a legacy library, `node-riffraff-artefact` (with an e), instead of `node-riffraff-artifact` (with an i).
Ever-so-minor improvement to DevEx 👩‍💻
> Update node-riffraff-artifact repo links

- riff-raff/app/schedule/DeployJob.scala
We've had an issue in the mobile team where some of our EC2 image got out of date even though we had a weekly scheduled deployment.
Upon investigating we found out two of our projects (`mobile-n10n:notificationworkerlambda` and `mobile-n10n:notification`) have a name including the other, and riff-raff could pick the wrong one.
@twrichards Quickly pointed out the potential use of the `isExactMatchProjectName` flag.
If we deploy the right project.
Riff-raff fails to deploy on a schedule.
YES
> Ensure scheduled deploys are matched exactly.

- magenta-lib/src/main/scala/magenta/Credentials.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/FastlyTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/main/scala/magenta/tasks/gcp/Gcp.scala
- magenta-lib/src/test/scala/magenta/tasks/AWSTest.scala
- riff-raff/app/resources/PrismLookup.scala
- riff-raff/test/lookup/PrismLookupTest.scala
Uses a less privileged role for most work but then uses a CFN service role when creating or updating CFN stacks.
This uses roles as defined in https://github.com/guardian/deploy-tools-platform/pull/209 
RiffRaff previously used a pile of static credentials to access other accounts. In #587 is was changed to assume a role to access other accounts but this had to be very powerful due to CFN stacks being created and updated.
This PR goes one step further. Riff-Raff assumes a least privileged role to make changes in another account and then uses a CFN service role to allow wide ranging changes to be made to resources.
Deploys still work and we can delete static credentials.
> Use service role for Cloudformation updates

- riff-raff/app/AppComponents.scala
- riff-raff/app/notification/GrafanaAnnotationLogger.scala
Grafana has an [annotations](https://grafana.com/docs/grafana/latest/reference/annotations/) feature that allows users to show lines on panels. We would like to add deployment lines to panels so that it is easier for users to correlate deployments with changes in metrics.
This is currently done using a bit of a hacky query (`"Editorial Tools::Integration Tests" AND "Started deploying" AND app:"riff-raff"`) in Grafana, and the log lines do not necessarily dictate the actual start of a deployment.
This PR adds loglines to  
Deploys in Riff-Raff create log entries as shown below, so that Grafana can query them for deployment annotations.
Before: using the message field in the logs to parse tags
New: example loglines (from Riff-Raff CODE deploys)
> Add logging for Grafana annotations

- riff-raff/app/resources/PrismLookup.scala
This is a temporary workaround while we investigate why newer Xenial AMIs aren't booting.
We're only selecting AMIs backed before Wednesday morning when applying an AMI update to limit the risk of breaking existing deploys while we investigate the ongoing Xenial incident.
Unit tests + deploy on CODE
Limit downtime and ASG disruptions
Yes, anyone working specifically on getting a new AMI might be very confused after this is merged.
> Only pick AMIs before Wednesday morning when updating AMIs

- riff-raff/app/resources/PrismLookup.scala
Reverts guardian/riff-raff#596
This change was introduced to prevent us launching instances with broken AMIs. We've now fixed the broken AMIs and can remove the change to continue to use the latest AMIs available in AMIgo 🎉 .
A few teams have confirmed the new AMIs are good and all the impacted recipes in AMIgo have had a bake triggered. This change should be good to go.
> Revert "Only pick AMIs before Wednesday morning when updating AMIs"

- riff-raff/app/assets/stylesheets/magenta.less
Increases the contrast between text and background on a row with warnings. This makes it easier to read the text.
Deploy to CODE.
Text is easier to read.
n/a
> improve text contrast on warning rows

- riff-raff/public/docs/reference/build.json.md
- riff-raff/public/docs/riffraff/hooksAndCD.md
We've recently updated this repo to use `main` as the default branch instead of `master`.
This PR updates some files in the repo to reflect this. I've stricken through `master` to imply its legacy. These files are documentation, until all our repos have been migrated, the docs should support legacy default branches.
Note, some tests still reference `master`. I'm not sure if it is worth updating those too?
﻿
> Update to more inclusive language.

- riff-raff/app/views/preview/yaml/showTasks.scala.html
In the preview screen, when you have lots of tasks but only want to kick-off some at the top, it's annoying to have to scroll all the way down.
Also, the "run tasks" label isn't active, i.e. the HTML should be
```html
<input type="checkbox" id="selectedKey_1">
<label for="selectedKey_1">Run tasks</label>
```
so that when you click on the text, it (de)activates the checkbox.
**Before (preview, deploy, reset not at top)**
**After (preview, deploy, reset at top and bottom**
> Minor UI improvements

- riff-raff/app/deployment/Deployments.scala
Log the branch being deployed as a marker. This is primarily to help understand our progress of moving from `master` to `main`.
Logging this information as a marker means we can create graphs within the Central ELK stack.
A graph of branch name used over time would allow us to track our progress of `master` to `main`; `master` reaching 0 is a proxy for our success on this work.
- Deploy to CODE
- Perform a deploy
- Witness log lines have extra markers
We have visibility of which branch is being deployed within the logs.
I think this log line occurs pretty close to the start of a deploy. That is, we don't know if the deploy has succeeded or not. I think this is fine as we only really care about deploying intent for this particular use case.
**Log filter (logs from RIffRaff CODE)** …
> decorate log line with extra information

- magenta-lib/src/main/scala/magenta/deployment_type/GCS.scala
- magenta-lib/src/main/scala/magenta/deployment_type/GcpDeploymentManager.scala
- magenta-lib/src/main/scala/magenta/tasks/gcp/DeploymentManagerTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/gcp/GCP.scala
- magenta-lib/src/main/scala/magenta/tasks/gcp/GCPRetryHelper.scala
- magenta-lib/src/main/scala/magenta/tasks/gcp/GCSTasks.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
- project/Dependencies.scala
- riff-raff/app/AppComponents.scala
Adds a task to deploy artifacts to Google Cloud Storage.
Use the `gcp-gcs` deployment type in `riff-raff.yml`.
Deployments to GCS succeeds.
None, since the task is new.
> Support for GCS deployment type

- riff-raff/app/views/deploy/deployInfoData.scala.html
- riff-raff/app/views/deploy/deployInfoHosts.scala.html
This PR adds the `activeTab` parameter in the call when using the `tabbable` snippet. This value is taken from the appropriate query parameter. This allows the active tab to be preserved across page refreshes.
On PROD navigate to `/deployinfo/hosts` and/or `/deployinfo/data` and select a tab that isn't the first. Refresh the page and you'll see that the first tab becomes active again. 
Repeat on the current branch and you should see that the previously selected tab is shown still.
The selected tab is persisted across page refreshes.
> Add activeTab parameter from querystring in order to preserve tab on page refresh

- riff-raff/app/assets/javascripts/auto-refresh.coffee
- riff-raff/app/views/deploy/dashboard.scala.html
- riff-raff/app/views/deploy/history.scala.html
- riff-raff/app/views/deploy/viewDeploy.scala.html
- riff-raff/app/views/preview/yaml/preview.scala.html
This PR updates the `auto-refresh` script and the views that make use of it in order that loading and error messages are shown around the auto update process. Those components that auto refresh now contain `loading`, `error` and `content` div tags. While the request is loading, the `loading` div is shown. If the request results in an error, the `error` div is displayed. The current content is left unchanged. If the request is successful then the `error` div is hidden and the `content` div is populate with the result of the request. 
The inspiration for this change was confusing behaviour when an error occurred on the `/deployment/history` page where when an error occurred the loading message continued to be shown with no change.
You can test the loading message by navigating to any page …
> Show loading and error status for auto refreshing components

- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
We ran into an issue using the `aws-s3` deployment type where the default value for publicReadAcl (true) doesn't play nicely with the default policy for new buckets, which is to restrict all public access. Update the docs to specify that if your bucket blocks public access then you should set this param to false.
Slightly clearer docs == slightly happier developers 👩‍💻 👨‍💻
> Update the docs for aws-s3 param publicReadAcl

- riff-raff/app/AppComponents.scala
- riff-raff/app/notification/DeployFailureNotifications.scala
- riff-raff/app/schedule/DeployJob.scala
- riff-raff/app/schedule/DeployScheduler.scala
This change refactors the code so that we are able to send failure notifications if scheduled deploys fail to start.
At the moment, we will not actually send notifications. Instead, we will log an event whenever we _would have_ notified a team, so that we can collect data on the common failure scenarios and work out how to resolve them.
Once we've done this, it should be trivial to start sending notifications in these scenarios.
Prior to commenting out the line which sends the notifications to Anghammarad, we confirmed that this was working as expected.
We've also tested that deploy failure notifications for other scenarios (e.g. a scheduled deploy which fails after starting due to lack of capacity) still results in a message being sent to Anghammarad.
Existing failure notifications …
> Prepare to send notifications if scheduled deploys fail to start

- riff-raff/public/docs/howto/fix-a-failed-deploy.md
This is a documentation fix for https://riffraff.gutools.co.uk/docs/howto/fix-a-failed-deploy. Prior to this change, it advised colleagues to use the CLI when actually this can be fixed in the AWS console with https://github.com/guardian/riff-raff/pull/507
> Update docs: how to fix a failed deploy

- riff-raff/app/controllers/Restrictions.scala
- riff-raff/app/deployment/model.scala
- riff-raff/app/notification/DeployFailureNotifications.scala
- riff-raff/app/notification/FailureNotificationContents.scala
- riff-raff/app/schedule/DeployJob.scala
- riff-raff/test/notification/FailureNotificationContentsTest.scala
- riff-raff/test/schedule/DeployJobTest.scala
This PR continues the work started in https://github.com/guardian/riff-raff/pull/611. We have identified the common reasons for scheduled deploys failing to start and are now ready to start sending notifications in these scenarios. 
Where there is a clearly identifiable owner and set of recovery actions, we will notify teams directly.
However, some alerts will be sent to the maintainers of Riff-Raff, rather than the teams who 'own' the scheduled deployments. There are two reasons for this:
1. In some scenarios teams are not actually empowered to fix the problems for themselves (e.g. 'stuck' deploys). Consequently these alerts will also be sent to Riff-Raff maintainers so that we can try to fix the underlying problem(s).
2. In some scenarios (e.g. configuration issues) we lack information …
> Enable failure notifications if scheduled deploys fail to start

- riff-raff/app/notification/DeployFailureNotifications.scala
I accidentally removed some [useful logging](https://github.com/guardian/riff-raff/pull/614/files#diff-0dceec64b87cbc45ffb3aabb2b6f1fb0abd9b04fcc1e1cde546cd01b49275362L81) in https://github.com/guardian/riff-raff/pull/614. This PR reinstates logging in the failure case so that we can debug problems more easily.
> Add logging in cases where notification target search fails

- riff-raff/riff-raff.yaml
Switches riffraff to using the [arm 64 deploy tools bionic recipe](https://amigo.gutools.co.uk/recipes/arm64-bionic-java8-deploy-infrastructure).
Deploy riffraff, wait for a quiet time on CODE/PROD and then terminate th riffraff instance
I've tested this on CODE and was able to perform a deploy succesfully
> Switch to ARM64 recipe

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
This PR removes some unnecessary information from [Riff-Raff's documentation page](https://riffraff.gutools.co.uk/docs/magenta-lib/types).
Historically, teams managed their own Riff-Raff users. Consequently, they needed to ensure that these users had the correct IAM permissions to support various Riff-Raff deployment types. 
Riff-Raff now assumes [a role](https://github.com/guardian/deploy-tools-platform/blob/main/cloudformation/riffraff/riffraff-roles.yaml) which is maintained by DevX. Consequently, other teams / users don't need to think about the IAM permissions which support various deployment types. Similarly, they no longer need to take any steps to add permissions to IAM users.
For more details on the new approach, see [new …
> Update deployment types documentation

- riff-raff/app/restrictions/RestrictionChecker.scala
- riff-raff/app/views/restrictions/form.scala.html
- riff-raff/test/restrictions/RestrictionCheckerTest.scala
Giant has restrictions on who can deploy it which form part of our defence in depth strategy as it can contain sensitive data. There is an issue currently where it stalls processing work after a few days and so we set up a daily scheduled deploy to keep it available for users whilst we investigate the underlying issue.
Unfortunately the scheduled deploy didn't work:
```
Scheduled deploy failed to start due to Error(Unable to queue deploy as restrictions are currently in place: Michael Barton: Sensitive data). A notification will not be sent...
```
We had configured the restriction to allow continuous deployment but scheduled deploys were still not allowed. This PR changes the behaviour to allow both if the checkbox is set and updates the description accordingly.
It's fully unit tested but …
> Permit scheduled deploys when restrictions are enabled if CD is enabled

- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
We currently have the ability to set the `cache-control` header on the `aws-s3` task.
I'd also like to be able to set the [surrogate-control](https://docs.fastly.com/en/guides/configuring-caching#surrogate-control) header as well.
> s3 - surrogate cache parameter

- riff-raff/app/assets/stylesheets/magenta.less
This highlights all row hovered in tables, not just clickable ones.
Hover over tables outside of the deployment history and get the same highlighting, minus the `pointer`.
More accessibility and confidence in making changes on long lists.
> Highlight all table rows

- riff-raff/app/assets/stylesheets/magenta.less
Changes the colour of the check mark from white to green for more visibility. This may not be totally accessible; feedback wanted!
Dark mode:
Light mode:
Dark mode:
Light mode:
> feat: green check mark

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
We'd like to better protect users from accidental resource deletion or changes that will replace a resource. For a sub set of resource types this can be destructive so we no longer allow such updates when Riff-Raff is configured to manage the stack policy. 
Riff-Raff can be configured to manage stack policies either by directly setting the `manageStackPolicies` setting in a `riff-raff.yaml` config file or targetted against multiple projects by configuring the `cloudformation:manage-stack-policy` key in the lookup service (Prism data).
This will need a permission change (https://github.com/guardian/deploy-tools-platform/pull/471) and setting `manageStackPolicies` to true in another project to try it out (https://github.com/guardian/prism/compare/sihil/riff-raff-stack-policy-management).
If …
> Apply stack policies before and after CFN updates

- magenta-lib/src/main/scala/magenta/Project.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/TaskResolverTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTasksTest.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/deployment/DeploymentEngine.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/deployment/preview/PreviewCoordinator.scala
- riff-raff/conf/application.conf
- riff-raff/test/deployment/actors/DeployGroupRunnerTest.scala
- riff-raff/test/deployment/preview/PreviewTest.scala
When migrating from AWS SDK v1 to v2 the S3 Upload was changed to buffer the entire file being uploaded from bucket A to B in memory. This created extra memory pressure (and has caused some deploys to fail when they have particularly large artifacts being copied when there is contention with other deploys) so this change switches back to streaming with a 1Mb buffer.
Due to the way that this is now implemented, the get and put requests must be on different threads. In order to facilitate this we add an isolated execution context for IO which is now passed around so tasks can use that when appropriate.
Pretty much any deploy will hit this path and so issues will likely become apparent fairly quickly. This has been tested in CODE to deploy itself. On a very small sample it seems to be around …
> Stream the S3 data rather than buffer entirely in memory

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- project/Dependencies.scala
- riff-raff/public/docs/riffraff/advanced-settings.md
#623 and #626 put us in a place that we can enable policy management for CFN stack updates. This will significantly reduce the risk of CFN updates making inadvertently destructive changes.
All deploys that update cloudformation
Ultimately this should reduce the number of incident retrospectives caused by accidental destructive cloudformation changes.
If teams are already using CFN stack policies then this will override them and discard what they have. This could leave them in an unexpected state where they do not have protection from their policies. We should confirm this before rolling this out by doing one of the following:
- Deploying this [Prism PR](https://github.com/guardian/prism/pull/197) that allows us to interrogate all CFN stacks to see if any use policies. This has not yet …
> Default to managing stack policies

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/ElasticSearch.scala
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/ElasticSearchTasks.scala
- magenta-lib/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTasksTest.scala
This PR refactors the way that Riff-Raff identifies which ASG to interact with as part of an `autoscaling` deployment.
Previously, Riff-Raff would search for the relevant ASG (by tags) as part of every individual task (e.g. `WaitForStabilization`) in a deployment action (e.g. `deploy`). Accounts can have many ASGs and the `deploy` action is comprised of many tasks, so this is inefficient. It's also unnecessary, as once we have selected the ASG to deploy to, we should perform all actions against the same ASG.
This PR refactors the code to identify the relevant ASG (still using tags) before starting _any_ tasks. Each individual task can then simply ask for the latest state of the specific ASG it cares about, rather than searching through all ASGs in the account. This allows us to simplify …
> Refactor ASG search

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/ElasticSearch.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
In order to migrate an application from its current (CloudFormation-defined) infrastructure to new (cdk-defined) infrastructure, Riff-Raff must be able to update two Autoscaling Groups (for the same`App`) as part of a single deployment. Prior to this PR it was impossible to do this. 
This PR allows users to instruct Riff-Raff to update both of their Autoscaling Groups by setting a new parameter in their `riff-raff.yaml`. Riff-Raff will check that it's safe to proceed by ensuring that it finds Autoscaling Groups with appropriate tags. If it finds any other AutoScaling groups for the same `App`/`Stack`/`Stage`, it will still refuse to proceed with the deployment.
* I have confirmed that deploys which _do not_ set this parameter are unaffected.
* I have confirmed that deploys which set this …
> Add support for dual-ASG deployment (in support of cdk migration)

- riff-raff/app/persistence/RestrictionConfigDynamoRepository.scala
We want to rename "whitelist" to "allowlist" because language matters.
In order to do this safely, we need to perform a three step dance:
1. Add the new field
2. Read the new field
3. Remove the old field
This ensures we can continue to read the data at all times, at the cost of three separate changes.
This is the first step.
It is done in a hacky way by mutating the DynamoDb table in the `GET /deployment/restrictions request`. It's hacky as it makes this route, temporarily, non-idempotent.
- Deploy to CODE
- Make a request to `/deployment/restrictions`
- Observe it continuing to work
- Open the DynamoDb table for CODE (riffraff-restriction-config-CODE) and observe the new column
The GET request will take a little longer as it's now updating the table. There aren't that many items in …
> chore: Add `allowlist` field to DynamoDb

- project/plugins.sbt
- script/ci
[Best practice](https://github.com/guardian/recommendations/blob/master/continuous-integration.md#platforms) has been defined as having a `script/ci` file in the repository to get the benefits of VCS.
This change also makes the TeamCity build more accurate. We're currently using the `sbt` runner in TeamCity which always exits 0, even when there are failing tests! This results in artifacts being always uploaded. This is undesirable! As an example, build [1632 failed](https://teamcity.gutools.co.uk/buildConfiguration/Tools_Riffraff/678317) but is available to be deployed and [did](https://riffraff.gutools.co.uk/deployment/history?projectName=tools%3A%3Ariffraff&stage=PROD&pageSize=20&page=1)!
This requires a change to the TeamCity configuration and other branches would need to rebase in …
> chore: Follow CI best practice

- riff-raff/app/conf/context.scala
- riff-raff/app/persistence/RestrictionConfigDynamoRepository.scala
Requires #638.
Our language should be more inclusive in 2021. This change removes `whitelist` from the codebase after the migration in #638.
As noted in #637 this is a three step dance:
1. Add the new field
2. Read the new field
3. Remove the old field
This is step 3.
- Deploy to CODE, the app should continue to work
- Make a request to `/deployment/restrictions`
- Observe it continuing to work
- Open the DynamoDb table for CODE (riffraff-restriction-config-CODE) and observe the whitelist column being dropped
> chore: Remove `whitelist` from DynamoDb and config

- riff-raff/app/persistence/RestrictionConfigDynamoRepository.scala
Requires #639.
This reverts commit f102394756d5d977c4b46e45a506e81271d899a4 after #639 has been deployed to keep the codebase clean and make the `GET /deployment/restrictions request` route idempotent again.
> chore: Remove redundant cleanup logic

- magenta-lib/src/test/scala/magenta/PackageTest.scala
- project/Dependencies.scala
We want to start using some classes available in later versions of the AWS SDK, specifically classes that allow us to create/update CFN private types ([this](https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#aws-cloudformation-14) and [this](https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#aws-cloudformation-6)).
This change bumps the AWS SDK to the latest available and "fixes" an off by one error in the tests. I've been unable to determine the origin of the off by one error, so have attempted to rationalise it instead.
CI should pass.
We are able to add new features to Riff-Raff via the new functionality of the AWS SDK.
> chore: Bump AWS SDK version to 2.17.15

- build.sbt
https://github.com/guardian/riff-raff/pull/635 removed some of the system properties that we rilied on to populate the build info. This gets the information from the riff-raff plugin which means it will always be consistent with the data in the riff-raff manifest.
When deployed the data in the bottom right hand corner of Riff-Raff should be accurate.
> Fix buildinfo commit ID and build number

- riff-raff/app/assets/javascripts/form-autocomplete.coffee
- riff-raff/app/views/deploy/form.scala.html
This PR makes the **Favourite** and **Delete Favourite** buttons more accessible.
It does so by:
- Adding a title attribute (providing a hover tooltip).
- Adding an aria-label attribute (providing a button description for screenreaders).
Run [locally](https://github.com/guardian/riff-raff) or test on CODE, adding and removing a favourite deploy.
> Make the favourite button more accessible

- riff-raff/app/controllers/Application.scala
This PR adds an extra condition to the pattern matching which decides whether to render dynamic content for the types doc page or whether to simply render the file contents of the markdown file found. 
This fixes an issue where the link from the `/docs/reference/riff-raff.yaml.md` page, directs you to `/docs/magenta-lib/types.md` which renders the contents of the `public/docs/magenta-lib/types.md` file instead of overriding it with dynamic content. 
**Question: would it be better just to update the link to point to `/docs/magenta-lib/types` instead?**
Navigate to both `/docs/magenta-lib/types` and `/docs/magenta-lib/types.md` on production and see that for `/docs/magenta-lib/types.md`, the following string is displayed: 
`This document is dynamically replaced when viewed inside the …
> Render dynamic content for both `types` and `types.md`

- riff-raff/app/utils/VCSInfo.scala
- riff-raff/test/utils/VCSInfoTest.scala
I noticed that the repo URL for frontend is https://github.com/guardian/frontend.git. Afaict this works fine
everywhere except where we build a link to a commit from the `deployment/view` page where the link to the commit is broken due to a superfluous `.git` in the repo path.
> When linking, handle https github URLs with .git ext

- riff-raff/app/controllers/authentication.scala
- riff-raff/app/views/auth/list.scala.html
There are a few scenarios where only a superuser can perform a task.
Rather than guessing who is a superuser or reading the configuration for the app, add a column to `/auth/list`.
> feat: Show if a user is a superuser

- riff-raff/app/views/restrictions/list.scala.html
- riff-raff/public/docs/index.md
- riff-raff/public/docs/riffraff/restrictions.md
Adds short documentation for restrictions with information on how to resolve issues where a restriction is locked by an ex-colleague.
The doc is linked to from `/docs` and also `/deployment/restrictions`.
It will be useful to expose the list of superusers in the UI to save people from guessing or finding the value from config. I'm initially thinking of denoting superuser status within `/auth/list`. I'll do this in a separate PR - #647.
> docs: Add documentation for restrictions

- riff-raff/app/views/auth/list.scala.html
Following some feedback on #647 (https://github.com/guardian/riff-raff/pull/647#issuecomment-915938924).
By only showing when a user is a superuser, the list is visually easier to process as presence of something in the column means someone is a superuser.
> Improve rendering of superuser status

- project/Dependencies.scala
We've seen a few occurrences of CloudFormation events printing as `null` in the UI.
It's going to be tricky to replicate this in order to fix it so update the AWS SDK in the first instance.
> chore: Update AWS SDK to 2.17.35

- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
In https://github.com/guardian/riff-raff/pull/623 we introduced the concept of `sensitiveResourceTypes`. This is essentially a list of infrastructure resources that we don't want Riff-Raff to delete/replace during CloudFormation updates (unless the user has specifically enabled a more dangerous mode of deployment - see https://github.com/guardian/riff-raff/pull/626 and https://github.com/guardian/riff-raff/pull/627).
This PR adds resource types which manage DNS infrastructure to the list of `sensitiveResourceTypes`. 
This change should prevent users from accidentally deleting DNS records, which is particularly important now as we're about to allow/encourage users to manage NS1 DNS infrastructure via CloudFormation.
> Prevent deletion and replacement of DNS infrastructure

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
There's been an odd occasion where the CloudFormation log in Riff-Raff shows an event as `null`.
`resourceStatus` is an enum and from [the docs](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/cloudformation/model/StackEvent.html#resourceStatus--):
> If the service returns an enum value that is not available in the current SDK version, resourceStatus will return ResourceStatus.UNKNOWN_TO_SDK_VERSION. The raw value returned by the service is available from resourceStatusAsString().
That is [`resourceStatusAsString`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/cloudformation/model/StackEvent.html#resourceStatusAsString--) is safer to use.
> fix: Use safer `resourceStatusAsString` method

- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
Protect VPC resources from destructive changes when doing a Cloudformation deploy.
Try and delete things and see if RR says no.
Update: tested successfully:
Though interesting to note the error is a bit cryptic as resource is `*`. This is because we block updates to all resources and then apply a condition to that policy by type.
> Protect VPC resources from destructive changes

- riff-raff/public/docs/howto/fix-a-failed-deploy.md
Adding more documentation to account for dealing with scale-in protection, as this was an issue that had me confused for quite some time in attempting to redeploy.
More comprehensive documentation should lead to quicker bug squashing by developers
Scaring people away with too much reading?
> Adding more information to how to fix a failed deploy page

- riff-raff/app/assets/javascripts/form-autocomplete.coffee
- riff-raff/app/views/deploy/form.scala.html
I ❤️  the new favourite project feature in Riff Raff. This PR makes a couple of small tweaks to the UI:
I'd like to have the UI only allow you to favourite when you've entered a "real" project name, but I think this incremental improvement is worth adding along the way.
Before:
After:
Before:
After:
1. Try click the favourite star when the project name field is empty. The button should be disabled and a new favourite should not be added.
2. Favourite a project, then try favouriting the same project again. A duplicate should not be added.
> Tweaks to favourite project UI

- build.sbt
- riff-raff/bootstrap.sh
- riff-raff/riff-raff.yaml
Switch from Java 8 to Java 11. There are potential performance gains but the main motivation is that some libraries require Java 11 now to function.  Specifically the Guardian's Play Secret Rotation library ultimately depends (via https://github.com/guardian/play-secret-rotation/blob/main/build.sbt#L18) on https://github.com/ben-manes/caffeine/releases/tag/v3.0.0 which required Java 11 to work.
When running with Java 8 the following error is seen:
java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/github/benmanes/caffeine/cache/Weigher, offset=6
In theory this should *just work*. But we will test on CODE.
> Use Java 11

- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentResolver.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/ci/TargetResolver.scala
- riff-raff/app/notification/DeployFailureNotifications.scala
Currently, we validate the `riff-raff.yaml` before identifying targets for an Anghammarad notification. This is fine until we change the rules for what makes a valid `riff-raff.yaml` file!
In this change we remove the validation step and instead use the raw YAML file.
See https://github.com/guardian/riff-raff/pull/665 which is causing deployments to fail if they are missing a parameter.
In the scenario where a deployment fails due to a missing parameter in `riff-raff.yaml`, teams continue to get notified directly.
> fix: Use raw YAML to determine Anghammarad targets

- magenta-lib/src/main/scala/magenta/tasks/gcp/GCP.scala
- project/Dependencies.scala
[(re https://github.com/guardian/riff-raff/pull/666](https://github.com/guardian/riff-raff/pull/666#issuecomment-1010990152)
The error seen is:
software.amazon.awssdk.core.exception.SdkClientException Unable to marshall request to JSON: Can not write a field name, expecting a value
And it is kicked off here:
magenta.tasks.UpdateS3Lambda.$anonfun$execute$7(tasks.scala:263)
though ultimately is thrown from the AWS SDK.
It's a bit unclear why this has broken. The surrounded code has not been changed by the upgrades PR. And there are not many similar reports, but an example is:
https://github.com/aws/aws-sdk-java-v2/issues/2875
As the inputs to the call look okay (we log them in the build) for now bumping the library makes sense as a first effort at a fix.
> Attempt fix of scheduled deploys issue

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
Easiest to review [w/out whitespace](https://github.com/guardian/riff-raff/pull/671/files?diff=split&w=1).
The `cloud-formation` deployment type in Riff-Raff has a number of steps (well, [tasks](https://github.com/guardian/riff-raff/blob/3bf2aa3529fda6f536a698c712c0186812147477/magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala#L135-L184)):
1. Set the update policy on the CloudFormation stack to guard against deleting stateful resources
2. Create a [ChangeSet](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-changesets.html)
3. Execute the ChangeSet
4. Watch the CloudFormation event log to determine when 3 has finished
5. Revert 1
Currently in step 4, we're only looking at the _first_ page of CloudFormation events and we expect …
> fix: Handle no-op ChangeSets more gracefully

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
In https://github.com/guardian/riff-raff/pull/671 we made some changes exiting early if a ChangeSet does not yield any changes. We accomplished this by calling `DescribeChangeSet` within `CheckUpdateEventsForChangeSetTask`. This happens  _after_ `ExecuteChangeSetTask` but it is too late! It appears a ChangeSet cannot be described by _name_ once it has been executed; it can only be described using the _ARN_.
<details>
<summary>CLI examples of `DescribeChangeSet` oddities</summary>
This fails:
```console
➜ aws cloudformation describe-change-set --change-set-name deploy-1642157037866 --stack-name REDACTED
An error occurred (ChangeSetNotFound) when calling the DescribeChangeSet operation: ChangeSet [deploy-1642157037866] does not exist
```
Whereas this passes:
```console
➜ aws cloudformation …
```
> fix: Poll CloudFormation events within `ExecuteChangeSetTask`

- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
The aim of this is to follow the existing style in the repo where the [`CloudFormation` object](https://github.com/guardian/riff-raff/blob/6572e28a24e657af5406a70d8fd44fa2cb841892/magenta-lib/src/main/scala/magenta/tasks/AWS.scala#L354) makes requests to AWS.
This is a no-op.
> refactor: Push ChangeSet logic into the `CloudFormation` object

- riff-raff/app/controllers/Application.scala
- riff-raff/conf/routes
This PR prevents users from accessing some problematic functionality which is currently causing the application to crash. We will other reinstate this functionality (or tidy it up properly) when we understand the issue/functionality better.
> Hide problematic /deployinfo/hosts page

- riff-raff/public/docs/howto/fix-a-failed-deploy.md
Improve the formulation of "Fixing a failed deploy" to be more useful after we encountered a bad case of failed deploy in frontend causing multiple stack to not fall back all the way to the desired capacity, and the fact that the previous version wasn't really explaining what to do and why.
> Improve: Fixing a failed deploy

- readme.md
- riff-raff/app/AppComponents.scala
- riff-raff/app/conf/context.scala
Adds a region and credentials provider for the SSM client we use to fetch the play application secret. This was done to avoid a common error on startup, when a users `default` profile would be used instead of `deployTools`. I believe the important addition is `ProfileCredentialsProvider.create("deployTools")` from the `credentialsProviderChain` we are now utilising. Presumably this worked for some people depending on their local AWS defaults.
While I was there, I also noticed an incorrect link on the readme.
Works locally, but I'll try it on CODE just in case the provider chain fails there. We just need the application to load.
> Specify region and provider for SSM client to help with running locally

- project/Dependencies.scala
This PR addresses a critical vulnerability flagged by snyk on quartz v2.3.0
Me and @NovemberTang paired on this and we updated the quartz package to its most recent version, which doesn't have any known vulnerabilities.
This is a patch version update, so it shouldn't break any functionality. Happy for suggestions on this front, as it's unclear to us what features quartz is used for and could be broken by this update.
Some automated process on riff raff grinding to a halt, probably scheduled deployments?
> Fix critical vulnerability by updating quartz version

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
The description for `manageStackPolicy` states that the default is `true` but in the `Default` column it is incorrectly listed as having `<no default>`. This PR should fix the docs.
> Correct documentation for CFN deployment type

- .gitignore
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/ci/CIBuild.scala
- riff-raff/app/utils/VCSInfo.scala
- riff-raff/test/docs/DeployTypeDocsTest.scala
- riff-raff/test/utils/VCSInfoTest.scala
Adds a `vcsUrl` tag to Cloudformation stacks on update to clarify ownership and discoverability.
Tested successfully on CODE:
> Add VCS URL tag

- riff-raff/app/AppComponents.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/controllers/Management.scala
- riff-raff/app/lifecycle/ShutdownWhenInactive.scala
- riff-raff/conf/routes
There is a requirement to keep the age of our AMIs down. We achieve this in (most) apps via the [ami-cloudformation-parameter](https://github.com/guardian/riff-raff/blob/13fdb406e8ea032f0a3843682abc7be4e84e5aa8/magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala#L9-L15), [auto-scaling](https://github.com/guardian/riff-raff/blob/13fdb406e8ea032f0a3843682abc7be4e84e5aa8/magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala#L93-L104) deployment types, and scheduled deploys.
An `auto-scaling` deployment is not possible with Riff-Raff, instead it [employs](https://github.com/guardian/riff-raff/blob/main/riff-raff/riff-raff.yaml) a [self-deploy](https://github.com/guardian/riff-raff/blob/13fdb406e8ea032f0a3843682abc7be4e84e5aa8/magenta-lib/src/main/ …
> feat: Add `/requestInstanceRotation` endpoint

- riff-raff/app/conf/context.scala
- riff-raff/app/persistence/IAMPasswordProvider.scala
We're moving away from V1 of the AWS SDK. In this change we rename `credentialsProviderChainV1` and add some documentation to that effect.
Follows from https://github.com/guardian/riff-raff/pull/691#discussion_r863574962.
> refactor: Rename `credentialsProviderChainV1` to `legacyCredentialsProviderChain`

- riff-raff/app/conf/context.scala
- riff-raff/app/lifecycle/ShutdownWhenInactive.scala
- riff-raff/app/notification/DeployFailureNotifications.scala
Requires https://github.com/guardian/riff-raff/pull/696 and addresses https://github.com/guardian/riff-raff/pull/691#discussion_r863641027. Helps to keep things DRY.
Ultimately, I think we should be getting this information from Parameter Store. However that'll require a revisit to how this application achieve's configuration, which is out of scope for this PR.
> refactor: Move config for Anghammarad into it's own section

- riff-raff/bootstrap.sh
Although #693 created a timer for Riff-Raff to self terminate, the timer was not activated. Oops!
> fix(rotation-timer): Ensure the instance rotation timer is started

- magenta-lib/src/main/scala/magenta/input/models.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentResolver.scala
- magenta-lib/src/main/scala/magenta/input/resolver/DeploymentTypeResolver.scala
- magenta-lib/src/test/scala/magenta/input/RiffRaffYamlReaderTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentGraphActionFlatteningTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentPrunerTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTasksGraphBuilderTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTypeResolverTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/TaskResolverTest.scala
- riff-raff/app/assets/javascripts/form-autocomplete.coffee
- riff-raff/app/controllers/Application.scala
- riff-raff/app/controllers/DeployController.scala
- riff-raff/app/deployment/actors/DeployGroupRunner.scala
- riff-raff/app/views/deploy/form.scala.html
- riff-raff/conf/routes
- riff-raff/public/docs/reference/riff-raff.yaml.md
- riff-raff/riff-raff.yaml
e.g.
```
stacks:
- deploy
regions:
- eu-west-1
allowedStages:
- INFRA
deployments:
...
```
The new field is optional and takes a list of (string) stages.
If present, these stages are used in the UI dropdown when doing a manual deploy. New default behaviour for stage is also added:  first sorting the list, CODE (if allowed) is preferred, then the first non-PROD stage, and failing that the first stage is used.
Deploys (of any kind) fail if allowedStages is non-empty and does not contain the stage being deployed to.
Stage is now disabled initially:
Selecting a build (in this case with a riff-raff.yaml containing `allowedStages`:
Stages are limited to those specified as allowed in the riff-raff.yaml file and 'CODE' is defaulted:
If you attempt a deploy to a disallowed stage, either through …
> Add allowedStages

- riff-raff/riff-raff.yaml
(Follow on from https://github.com/guardian/riff-raff/pull/692.)
Fixes the deploy of main, which currently can't deploy as the old main doesn't recognise this new riff-raff.yaml field.
Once merged and deployed, I'll raise a quick PR to re-add these lines.
Unfortunately this was not discovered during testing because I initially deployed the allowed stages branch to CODE pre adding these lines.
> Temporarily remove this to fix the deploy

- riff-raff/riff-raff.yaml
Follow-on from https://github.com/guardian/riff-raff/pull/699 to reinstate now that `main` recognises the fields.
> Re-add configuration

- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
Whilst working on https://github.com/guardian/cdk/pull/1308, I realised that there were a couple more API Gateway resources that should not be deleted unless the user explicitly opts-in to `Dangerous` mode!
I've deployed this to `CODE` and confirmed that a CFN deployment still works.
Users are less likely to accidentally remove important resources, making downtime/incidents less likely.
If we add invalid items to this list it can break deployments, but this risk should be mitigated by testing in `CODE`.
> Protect some more API Gateway resources

- riff-raff/app/notification/DeployFailureNotifications.scala
- riff-raff/app/notification/FailureNotificationContents.scala
In some scenarios (e.g. if there is a malformed `riff-raff.yaml`), Riff-Raff cannot figure out where to send failed deployment notifications. To avoid dropping these alerts completely, we aim to send them to a fallback destination. The intention here was that these alerts should go to DevX/Riff-Raff maintainers, so that we can help to forward these on to the correct team and/or fix any failed deployments that occur due to bugs in Riff-Raff.
The exact email address that gets used for this fallback is defined via the Anghammarad config:
`"target": { "Stack": "deploy", "Stage": "PROD", "App": "riff-raff" }`
Recently this mapping has been updated. We now send alerts via Chat messages to the `DevX Stream` (public) channel and emails to the whole Engineering department. This is useful in some …
> Update targets for notifications where correct team cannot be identified

- riff-raff/app/controllers/Management.scala
- riff-raff/bootstrap.sh
- riff-raff/conf/routes
Reverts guardian/riff-raff#695
This refactoring isn't quite complete, and prevented Riff-Raff PROD from starting today as `bootstrap.sh` was referencing a file that no longer exists.
Reverting, and will try again in a follow-up PR.
> Revert "refactor: Rename `rotate` to `terminate` for consistency"

- .github/workflows/dep-updates_pr-tracking-branch-to-default.yml
- .github/workflows/dep-updates_set-automerge.yml
- .github/workflows/dep-updates_tracking-branch.yml
Adds a series of workflows that enable granular dependency updates from e.g. Scala Steward. It works by automatically merging PRs from those tools into a non-default branch before creating a single PR on a specified schedule.
> Add workflows to enable dependency update batching

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
As part of the pre-flight checks for an `autoscaling` deployment, Riff-Raff will attempt to lookup the ASG, and throw an error if it's unable to locate any. This behaviour is desired when deploying to an _existing_ ASG. However if we want to _create_ a new stack (from nothing) it means we cannot use Riff-Raff for the initial creation and have to resort to going directly to AWS. 😢 
In this change, we change the rules. If an ASG cannot be located _and_ the update strategy is `Dangerous` (see #626), then allow the deployment to continue. This allows us to use Riff-Raff to deploy a new stack from scratch! 🎉 
Note: If an ASG cannot be located and the update strategy is `MostlyHarmless`, we continue to fail, but provide a hint to the `Dangerous` option.
This change is more pragmatic than …
> feat(autoscaling): Enable deployment to a new ASG

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
Requires #789, but only because I've branched off that.
For this `riff-raff.yaml` file:
```yaml
allowedStages:
- PROD
regions:
- eu-west-1
stacks:
- deploy
deployments:
backend-101-scala-starter-akash1810:
type: autoscaling
parameters:
bucketSsmLookup: true
```
Riff-Raff will define:
- package as `backend-101-scala-starter-akash1810`
- stack as `deploy`
- stage as `PROD`
When uploading the build artifact to S3, Riff-Raff will use the path:
```
s3://BUCKET/deploy/PROD/backend-101-scala-starter-akash1810/my-file.jar
```
The path can be customised via the [`prefixStage`, `prefixStack` and `prefixPackage` parameters](https://github.com/guardian/riff-raff/blob/1b457280690f4d4b74fd0638bb0dedcb4c82c2d4/magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala#L58-L66). In this change, …
> feat: Add `prefixApp` parameter to `autoscaling` and `aws-s3` deployments

- magenta-lib/src/main/scala/magenta/deployment_type/GCS.scala
- magenta-lib/src/main/scala/magenta/tasks/gcp/GCP.scala
- magenta-lib/src/main/scala/magenta/tasks/gcp/GCSTasks.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
The datatech team would like to refine the GCS deployment type previously implemented here: https://github.com/guardian/riff-raff/pull/604 and here: https://github.com/guardian/riff-raff/pull/574. We use this deployment type to update our CODE and PROD instances of [Cloud Composer](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjvta_i3Zv5AhXZgVwKHWgAC8cQFnoECAcQAQ&url=https%3A%2F%2Fcloud.google.com%2Fcomposer&usg=AOvVaw0BvoAUnha-00_IH8bqYzJs). This is the Google Cloud hosted implementation of [Apache Airflow](https://airflow.apache.org/]. 
For each deploy we upload a set of (mostly) python files to a GCS bucket. These files contain the [Dags](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html) defining the data-pipelines in …
> Delete obsolate files in Google Cloud Platform deploys

- .scala-steward.conf
- project/Dependencies.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/utils/ElkLogging.scala
Reverts guardian/riff-raff#802 to bring back the dependency update changes for this week. This time with a fix for the runtime issue encountered in the first attempt. We were (transitively) pulling in a new version of the v2 aws sdk (patch version 248), which turned out to be incompatible, at runtime, with the direct dependency on patch version 109.
> Revert "Revert "Dependency updates 2022-08-15""

- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
This PR fixes a bug which resulted in Riff-Raff setting the desired AutoScaling group capacity incorrectly (and therefore deployments failing / getting into a weird state). 
The bug was caused by obtaining information about the AutoScaling group at the _very start_ of the deployment and then failing to refresh this information as the deployment proceeded. I suspect that this underlying problem may have also caused some other rare bugs/unusual behaviour too. 
I believe the problem was first introduced via https://github.com/guardian/riff-raff/pull/650 (more specifically [here](https://github.com/guardian/riff-raff/pull/650/files#diff-486da3a5337f0a0aef4f7881a9bf7830015c76f51b82be67053132d3bdaae222L170-L176)).
We noticed this bug affecting some deployments yesterday. The problematic …
> Get the latest state of the ASG before every ASGTask

- .github/workflows/ci.yml
**Note, I have temporarily paused the Teamcity Riffraff build as part of this. We can unpause if we decide to rework this PR for any reason.**
*Note, the `riffRaffUpload` task has been temporarily removed until this is ready to merge to avoid clashing with Teamcity which isn't aware of other builds.*
Switch to GHA.
There are a few motivations here:
* move to GHA with associated benefits (CI in code, etc.)
* see whether as a result builds become less flaky (https://trello.com/c/nBdgDu2h/1432-move-riffraff-build-to-gha has details) - we'll probably only be able to answer this over time but it seems likely given the causes of some of the previous issues concern contention for resources on our Teamcity agents
* explore Scala GHA build times and to what extent larger runners help here (will do …
> Test out GHA builds

- readme.md
This fixes the link to the docs from the repo README
> Fix link to docs

- build.sbt
Explicitly configure the RIff-Raff project name following the move to GitHub Actions in #867, else we'd have to reconfigure the scheduled, continuous and restricted deployments.
> ci: Explicitly set Riff-Raff project name

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
In #623 we introduced a feature to protect stateful resources from being accidentally deleted. It is possible to opt-out of this with the `manageStackPolicy` flag, but it's not desired.
In this change we add a warning to the deployment log to surface the use of this flag.
The [consent-management-platform](https://github.com/guardian/consent-management-platform/blob/5b4b189303467d3d59c4cdc8c75b6e981691f159/riff-raff.yaml#L17) stack is one example of where we set `manageStackPolicy` to `false`. In this particular case, we're doing this because of a bug in Riff-Raff; Riff-Raff will apply [this stack policy](https://github.com/guardian/riff-raff/blob/fefe9f1df44f269edf6062ba928cf9127b52044c/magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala#L32-L73) in all regions, however the …
> fix: Add a warning message when `manageStackPolicy` is `false`

- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
- magenta-lib/src/test/scala/magenta/tasks/SetStackPolicyTaskTest.scala
> **Note**
> Easier to review [commit by commit](https://github.com/guardian/riff-raff/pull/874/commits).
Extends #653 to also check for regional availability of public AWS resource types. This is necessary because we've seen deployments fail in us-west-1 with:
```
software.amazon.awssdk.services.cloudformation.model.CloudFormationException Error validating stack policy: Unknown resource type 'AWS::DocDB::DBCluster' in statement {}
```
That is `AWS::DocDB::DBCluster` is not available in us-west-1.
This can be verified via:
```bash
➜ aws cloudformation list-types \
--visibility PUBLIC \
--type RESOURCE \
--profile deployTools \
--region us-west-1 \
--filters Category=AWS_TYPES \
| jq '.TypeSummaries[] | select(.TypeName == "AWS::DocDB::DBCluster")'
```
vs.
```bash
➜ aws cloudformation …
```
> fix(cloudformation): Detect regional availability of all resource types

- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
- magenta-lib/src/test/scala/magenta/tasks/SetStackPolicyTaskTest.scala
JSON formatting is hard...
We currently render a JSON array as:
```json
{
"ResourceTypes": [
"One",
"Two",
"Three"
]
}
```
That is, without indentation.
It should be:
```json
{
"ResourceTypes": [
"One",
"Two",
"Three"
]
}
```
However, there isn't much need to pretty-print this JSON blob as machines are the only consumers. In this change, we render a JSON array as a simple comma separated value:
```json
{
"ResourceTypes": [
"One","Two","Three"
]
}
```
This is functionally equivalent, and makes the tests simpler to read. That is, this is a no-op.
Also fixes a small typo.
See CI - all tests should continue to pass.
> refactor: Simplify JSON for stack policy

- riff-raff/app/assets/stylesheets/magenta.less
Update the CSS for the log to ensure a strict column is observed.
In https://github.com/guardian/riff-raff/pull/881 we removed some new lines from a JSON object. This object gets printed in the UI, and without the newlines, it's breaking through the column.
In this change, we use [CSS](https://caniuse.com/wordwrap) to ensure this doesn't happen.
N/A
https://riffraff.gutools.co.uk/deployment/view/5dd8d79f-0c42-4f9a-ab45-4171bddd8026 looks a bit nicer.
> **Note**
> The background colour was added via the browser to demonstrate the boundary.
> fix: Ensure log fits in a strict column

- magenta-lib/src/main/scala/magenta/deployment_type/BucketParameters.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
This enable to omit the `bucketSsmLookup` parameter, which reduce `riff-raff.yaml` verbosity.
This looks to me a detail that is not necessary especially if we expect people to use this over explicit `bucket` parameter.  
This should enable this:
```yaml
stacks:
- deploy
regions:
- eu-west-1
allowedStages:
- PROD
deployments:
cdk-playground:
type: autoscaling
parameters:
```
> Use bucket by ssm key by default

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- riff-raff/app/AppComponents.scala
Riffraff adds a `gu:repo` tag to Cloudformation stacks as part of the cloud-formation deployment type. This information is used by the nascent `services.gutools.co.uk` to help identify owners of stacks and related metadata.
However, in many cases, Riffraff is unable to populate this tag as it is unable to determine the repository for a build. The repository information is taken from the `vcsURL` field in the (build.json) 'manifest' file for a deployment and older build methods (or bespoke/script-based approaches) do not populate this. The latest versions of sbt-riffraff-artifact ([here](https://github.com/guardian/sbt-riffraff-artifact/blob/main/src/main/scala/com/gu/riffraff/artifact/BuildManifest.scala#L25)), node-riffraff-artifact …
> Warn if unable to determine Github repository for a deploy

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
The standard tags are: App, Stack, Stage.
These tags are required by services.gutools.co.uk to group related stacks (those which belong to the same 'App' and 'Stack' but differ by 'Stage'.
Many stacks already have these tags, but non-CDK ones may not.
Nb. this change will force stack updates for some stacks. This shouldn't be a problem but it may confuse teams without some advance comms. The plan is to do a joint email covering this and also https://github.com/guardian/riff-raff/pull/927 at the same time.
> Add standard tags as part of Cloudformation deployments

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- riff-raff/app/AppComponents.scala
- riff-raff/app/ci/CIBuild.scala
- riff-raff/app/ci/S3Build.scala
- riff-raff/test/ci/ContinuousDeploymentTest.scala
- riff-raff/test/ci/S3BuildTest.scala
- riff-raff/test/docs/DeployTypeDocsTest.scala
Adds the buildTool as a tag on Cloudformation deploys. This will help us to track usage of build tools for services. The particular focus is @guardian/actions-riff-raff but the solution is general.
Note, as part of this, the reporter error for missing vcsUrl has been removed - looking more closely at the code, I believe deploys should already fail if this is not present so the warning here is redundant.
See also: https://github.com/guardian/actions-riff-raff/pull/23.
> Record build tool

- magenta-lib/src/main/scala/magenta/deployment_type/BucketParameters.scala
Reverts guardian/riff-raff#942
It turns out that this changed the behaviour from before in the precise case when ssmBucketLook is not set (so defaults to *false*) but an SSM bucket is specified. In this case. Previously it would just use the specified ssm parameter, whereas now it was using the fallback/default SSM value.
> Revert "Introduce bucketSsmKeyStageParam"

- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
These tests frequently (perhaps 50% of runs or more) fail with:
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving class DescribeInstanceHealthResponse
A full test run with failures can be found [here](https://github.com/guardian/riff-raff/actions/runs/3676832331/jobs/6218284172).
We should fix this, but in the meantime let's ensure our tests are reliable.
> Disable flaky tests

- riff-raff/app/AppComponents.scala
Uses the correct value for the `gu:repo` and `gu:build-tool` tags.
TBD.
> fix: Use correct values for `gu:repo` and `gu:build-tool`

- magenta-lib/src/main/scala/magenta/deployment_type/BucketParameters.scala
- magenta-lib/src/test/scala/magenta/deployment_type/BucketParametersTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTasksTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
**~~TODO: in the process of writing some explicit tests for the BucketParameters trait.~~ DONE**
* [Original PR](https://github.com/guardian/riff-raff/pull/942) aimed to introduce stage support for `bucketSsmKeyParam`
* [Revert](https://github.com/guardian/riff-raff/pull/947) as the above broke the default behaviour
This PR restores the original PR while fixing the (accidental) breaking change that the original PR introduced - see the extra commit that ensures we default to SSM lookup even when `bucketSsmLookup=false`.
I have some quibbles with the clarity of this behaviour going forward, but it's not clear that we can change it now that the behaviour exists.
> Revert "Revert "Introduce bucketSsmKeyStageParam""

- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
Configure Riff-Raff to protect EFS, as it holds state.
Use-cases for EFS include persisting data across instance rotations, resulting in little/no service disruption. When an instance rotates into service, it'll mount the EFS volume and not need to rebuild any state, as it has it.
Examples include:
- Grid FTP using EFS to hold transferred images
- TeamCity server using EFS to hold configuration, logs, caches, etc
It's worth noting that, as ever, "Dangerous" mode will allow you to delete/replace these resources.
See https://docs.aws.amazon.com/efs/latest/ug/how-it-works.html.
> fix: Add `AWS::EFS::FileSystem` to set of protected resources

- magenta-lib/src/main/scala/magenta/deployment_type/LambdaLayer.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- riff-raff/app/AppComponents.scala
In order to deploy new versions of lambda layers via riff-raff in a sensible manner we should add support for an aws-lambda-layer deployment type to riff-raff.
Currently this is possible using the aws-s3 deployment type, but that mechanism results in complete replacement of the layer. This is unsuitable as if layers are being used to support devx functionality in our estate we must have a mechanism of safely updating those layers.
The deployment mechanism in riff-raff should use the [PublishLayerVersion](https://docs.aws.amazon.com/lambda/latest/dg/API_PublishLayerVersion.html) API in AWS to update layers creating new versions without replacing the layer (and consequently creating new ARNs each time).
Currently this deployment type will publish a new version every time it is deployed, and …
> Add Lambda Layer deployment type

- magenta-lib/src/main/scala/magenta/deployment_type/GCS.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
**Note: blocked by/depends on https://github.com/guardian/reuse-content/pull/40.**
Following on from https://github.com/guardian/riff-raff/pull/941 we can now delete this parameter too.
There is only a single user of this parameter, and the purpose (varying bucket by stage) is better achieved with the new [bucketSsmKeyStageParam](https://github.com/guardian/riff-raff/blob/23443fc9fe1fd8da5619cb74aef9be3d41376218/magenta-lib/src/main/scala/magenta/deployment_type/BucketParameters.scala#L31).
> Remove bucketResource

- CODEOWNERS
We're [requiring a review from CODEOWNERS to merge to main](https://docs.google.com/document/d/1MZb_9E8_PJtHR4QjbodvvYJrluNCMPlAhYsSucFuNE4/edit#), this should include the devx-reliability & devx-security team as responsibility for this tooling is shared.
> Add devx-reliability,  devx-security to CODEOWNERS

- CODEOWNERS
The current expected behaviour is that all devx teams listed can approve PRs, the actual behaviour is the last rule takes precedence and only devx-security can approve PRs. 
See also https://github.com/guardian/deploy-tools-platform/pull/666
> Fix CODEOWNERS to work as intended

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormationDeploymentTypeParameters.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
In https://github.com/guardian/riff-raff/pull/479 the parameter `amiEncrypted` was added to the `riff-raff.yaml` file, with the following behaviour:
- Default of `false`
- When `false`, Riff-Raff locates AMIs without the `Encrypted` tag, or where the tag is set to `false`
- When `true`, Riff-Raff locates AMIs with the `Encrypted` set to `true`
The value of `amiEncrypted` is applied to _all_ AMIs in the stack.
The `amiParametersToTags` parameter allows one to describe the characteristics of multiple AMIs in the stack, independently. However, it's not currently possible to set encryption independently across these AMIs.
In this change, we update the `getLatestAmi` logic to support the use-case where a stack has multiple AMIs, and where each can be encrypted, or not.
For example:
```yaml …
```
> fix: Observe `Encrypted` when set in `amiParametersToTags`

- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormationDeploymentTypeParameters.scala
The changes in #991 has caused https://riffraff.gutools.co.uk/deployment/view/58385bf3-b10f-47b3-afac-d9e53e1a7278 to fail.
This is because the `riff-raff.yaml` is:
```yaml
regions:
- eu-west-1
stacks:
- ophan
deployments:
big-loader-es7:
type: autoscaling
dependencies:
- update-ami
update-ami:
type: ami-cloudformation-parameter
app: big-loader-es7
parameters:
amiEncrypted: true
amiParametersToTags:
ImageId:
Recipe: ophan-ubuntu-bionic-ARM
AmigoStage: PROD
BuiltBy: amigo
```
That is, `amiParametersToTags/Encrypted` is not set, so `Encrypted=false` is used. However `Encrypted=true` should actually be used.
In this change we fallback to `amiEncrypted` if `amiParametersToTags/Encrypted` is absent.
Ideally, support for `amiEncrypted` would be dropped, however [multiple …
> fix: Fallback to `amiEncrypted` when `amiParametersToTags/Encrypted` is absent

- riff-raff/public/docs/howto/configure-a-project.md
Updates the docs for autoscaling to nudge people towards storing their bucket names in SSM rather than referencing directly since [bucket names are considered private information](https://github.com/guardian/recommendations/blob/main/github.md#private-information).
> docs: Update autoscaling docs to nudge towards using bucketSsmLookup

- riff-raff/riff-raff.yaml
Move to use https://amigo.gutools.co.uk/recipes/arm64-focal-java11-deploy-infrastructure.
This will allow us to:
- Move Riff-Raff to 20.04 to avoid the 18.04 EOL
- Test whether the new `arm64-focal-java11-deploy-infrastructure` image is working as expected
Deploy this PR to the CODE environment and check the EC2 instances with the new AMI are successfully brought into service & that we can access the Riff-Raff UI.
Riff-Raff's self-deployment process downloads a new artefact and restarts the service, to test (and deploy) this change we'll need to cycle the instance via the `requestInstanceRotation` endpoint.
This can be done as follows:
```
ssm cmd -t riff-raff,CODE -p deployTools --cmd "curl --silent -X POST localhost:9000/requestInstanceRotation"
```
See: …
> Use arm64-focal-java11-deploy-infrastructure as the AMI

- .github/workflows/ci.yml
This is an attempt to resolve the OOM errors we sometimes see in CI. The [`sbt` script in this repo](https://github.com/guardian/riff-raff/blob/1e1ca44746c4876fea1d58d36689775ca165dd2f/sbt) customises the amount of memory available.
Example of OOM seen in CI:
```log
[error] Caught java.lang.OutOfMemoryError: Metaspace
[error] To best utilize classloader caching and to prevent file handle leaks, we recommend running sbt without a MaxMetaspaceSize limit. 
[error] 
java.lang.OutOfMemoryError: Metaspace
[error] java.lang.OutOfMemoryError: Metaspace
```
A more stable build?
> ci: Use custom `sbt` script that configures memory

- magenta-lib/src/main/scala/magenta/deployment_type/S3.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3ObjectPrefixParameters.scala
- magenta-lib/src/test/scala/magenta/deployment_type/DeploymentTypeTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/S3ObjectPrefixParametersTest.scala
> **Note**
> Easiest to review [commit by commit](https://github.com/guardian/riff-raff/pull/1015/commits) as this change extracts some existing behaviour into a `trait` - [this specific change](https://github.com/guardian/riff-raff/pull/1015/commits/6b71973b00b5f2b04cb1c34e3381422a365e214f) should be considered a no-op.
In the `aws-s3` deployment type, the path within S3 that we upload to is controlled by the following parameters:
- `prefixPackage`
- `prefixStack`
- `prefixApp`
- `prefixStage`
This results in the path being the same regardless of the stage being deployed.
For example, for the file `image.jpg` and a _shared_ bucket the upload path will be something like `<bucket>/<STAGE>/image.jpg`. If the bucket was not shared across stages ([as …
> feat: Add `prefixStagePaths` parameter to `aws-s3` deployments

- riff-raff/app/deployment/model.scala
- riff-raff/app/schedule/DeployJob.scala
- riff-raff/test/schedule/DeployJobTest.scala
Recently, when @guardian/digital-cms were working on https://github.com/guardian/editorial-tools-production-monitoring/pull/316, they needed to do partial deploys (in order to test on secondary instances in PROD, but leave primary instances unaffected), meanwhile riff-raff performed the scheduled deploy for this project, **crucially a full deploy**, which in turn broke primary instances, this was quickly dealt with but perhaps if someone forgets that they did a partial deploy, then the current behaviour of riff-raff could cause some quite pernicious problems.
So now, if last deploy for a project was 'partial' then the scheduled deployed is skipped but users are notified (just like when previous deploy failed, as most likely the partial deploy was temporary).
> skip scheduled deploys where last deploy was 'partial' to prevent unexpected/problematic behaviour

- riff-raff/app/views/continuousDeployment/form.scala.html
- riff-raff/app/views/continuousDeployment/list.scala.html
Looking at projects with CD configured, it seems that the only type of configuration we use is to specify a branch name, which gets converted to a regex (by adding start and end anchors). Let's simplify the UI and make it clear you can enter a branch name, and expose that name back to users, rather than the constructed regex. I've gotten confused in the past and added the `^` and `$` manually, which isn't necessary (I see a few instances of `^^main$$` in the CD configurations, so I don't think I'm the only one!)
Displays branches as regexes:
Displays branch names:
Asks the user for a branch regex:
Asks the user for a branch name:
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with …
> Don't expose branch regexs for CD, just names

- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
Update the lambda deployment type to allow specifying whether to skip, stack, stage & app prefixed to lambda s3 location. This makes the deployment type more consistent with others (for example `autoscaling`), and is required for. https://github.com/guardian/cdk/pull/1838.
Deploy to https://riffraff.code.dev-gutools.co.uk/, and attempt to use this to successfully deploy https://github.com/guardian/birthdays/pull/75, and some existing projects including lambdas to ensure the current behaviour has not changed.
The `googleAuth` option in the `guEc2App` pattern can be used successfully by non-DevX teams.
Changing the lambda delpoyment type may impact existing users, thorough testing is needed!
> Add params for locating lambda artefact in S3 match autoscaling

- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
Displays a warning if an AMI cannot be resolved during a cloudformation deploy. For now this is a warning to see how often this happened, but I think we should upgrade this to an error
Deploy to CODE. Attempt to deploy a project that has a missing AMI.
> Warn if an AMI cannot be resolved during cloudformation deploy

- magenta-lib/src/main/scala/magenta/deployment_type/Fastly.scala
- magenta-lib/src/main/scala/magenta/deployment_type/FastlyCompute.scala
- magenta-lib/src/main/scala/magenta/tasks/FastlyComputeTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/FastlyTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/FastlyUtils.scala
- project/Dependencies.scala
`FastlyTasks` and `FastlyComputeTasks` currently share a few methods. When I introduced `FastlyComputeTasks`, I merely copy-pasted from `FastlyTasks`, but duplication of code is not great, so this PR attempts to fix that.
I have created a trait called `FastlyUtils` which `FastlyTasks` and `FastlyComputeTasks` now extend. It contains the following `protected` methods that are shared by both case classes:
- `block`
- `clone`
- `stopOnFlag`
- `getActiveVersionNumber`
- `commentVersion`
- `activateVersion` (abstract since implementation differs based on deployment type)
In particular, `commentVersion` is a new addition to the PR which is now available to the Fastly API client since v0.6.0. 
It lets Riff-Raff pass deployment information to Fastly, so the latest deployed version of the service …
> Refactor Fastly tasks, add comment to deployed version

- riff-raff/app/views/menu/appmenubar.scala.html
- riff-raff/app/views/menu/menubaritem.scala.html
The navbar has some keyboard-navigation problems currently - the Configuration and Documentation dropdowns can't be selected by keyboard, and the Profile dropdown is focused before all the other items (with an unclear focus state with no focus ring).
This PR makes two changes to the navbar:
1. Makes the dropdowns keyboard-navigable with a focus ring visible
2. Re-orders the items in the DOM so that the profile dropdown is last (rather than second) - matching how the menu appears visually
Run `riff-raff` locally or deploy to CODE according to the [instructions in the readme](https://github.com/guardian/riff-raff/blob/main/CONTRIBUTING.md).
Try navigating the menu with your keyboard. Can you select items with <kbd>enter</kbd> including the dropdowns? Do they show a focus ring?
| Before | …
> Improve keyboard navigation for navbar

- riff-raff/app/views/deploy/deployHistory.scala.html
- riff-raff/app/views/deployTarget/selectVersion.scala.html
- Changes the visual style of the `Riff Raff has not been used to deploy {{projectName}} to {{stage}}` alert from error to info, as I don't think this is an error state 
| Before | After |
|--------|--------|
| ![image](https://github.com/guardian/riff-raff/assets/705427/00fa6e3b-f710-4f89-888b-6bcb5f4c1351) | ![image](https://github.com/guardian/riff-raff/assets/705427/b2e06208-70e2-4a4b-a2e5-806379b133f0) |
> Use info instead of error alert style when project never deployed

- magenta-lib/src/main/scala/magenta/deployment_type/Lambda.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/LambdaTest.scala
- magenta-lib/src/test/scala/magenta/tasks/TasksTest.scala
This PR updates Riff-Raff so that it [tags](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html) Lambda artifacts when it uploads them to S3. 
Lambda artifacts are only needed temporarily[^1] and adding these tags will allow us to more easily cleanup unused Lambda artifacts (using lifecycle rules) in the future:
> Object tags enable fine-grained object lifecycle management in which you can specify a tag-based filter, in addition to a key name prefix, in a lifecycle rule.
The main motivation for adding this capability now is the fact that some teams are planning to start using Lambda versioning. This will mean that we have a lot more Lambda artifacts in our distribution buckets (see https://github.com/guardian/cdk/pull/1925 for more detail).
This change relies on an …
> Add S3 object tags to Lambda artifacts

- project/Dependencies.scala
Reverts guardian/riff-raff#1227, as this change prevented the app from starting.
I've confirmed this to be true by "redeploying"[^1] the previous build of main (3045), which has resolved the issue.
[^1]: With Riff-Raff being down, it is not possible to deploy Riff-Raff, so I manually copied the artifacts across S3 buckets.
> Revert "chore(deps): Non-AWS dependency updates"

- .github/workflows/ci.yml
- .sbtopts
- build.sbt
- project/plugins.sbt
Replaces the deprecated [sbt-riffraff-artifact](https://github.com/guardian/sbt-riffraff-artifact) with [guardian/actions-riff-raff](https://github.com/guardian/actions-riff-raff).
Some related changes are also made, including:
- [Setting up caching](https://github.com/actions/setup-java#caching-packages-dependencies)
- Using the native `sbt` that comes with [actions/setup-java](https://github.com/actions/setup-java)
This change should be a no-op in terms of the application. Therefore to test:
- Deploy this branch to CODE
- Observe the app still working
Indeed, I have [done just this](https://riffraff.code.dev-gutools.co.uk/deployment/view/b2a39629-32d1-4288-8b21-f5abcaf351a9).
One less repository using a deprecated library.
> ci: Adopt `guardian/actions-riff-raff` in favour of deprecated `sbt-riffraff-artifact`

- project/Dependencies.scala
It appears that later versions of `logback-classic` are not compatible with the version of `play-logback` as on app start, we get:
```log
[error] java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL)'
[error]         at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:125)
[error]         at play.api.libs.logback.LogbackLoggerConfigurator.init(LogbackLoggerConfigurator.scala:31)
[error]         at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:106)
[error]         at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
[error]         at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:76)
[error]         at …
```
> chore(deps): Configure Scala Steward to ignore `logback-classic`

- riff-raff/app/notification/FailureNotificationContents.scala
getting match errors....
...when notifying about `SkippedDueToPreviousPartialDeploy` introduced in https://github.com/guardian/riff-raff/pull/1082
In an ideal world, we could catch such exhaustiveness issues at compile time (beyond the scope of this PR though)
> add notification case for `SkippedDueToPreviousPartialDeploy`

- .github/workflows/ci.yml
- build.sbt
We're currently using the environment variable `GITHUB_RUN_NUMBER` to determine the build number for build info. `GITHUB_RUN_NUMBER` is not offset by the number of builds of this project previously performed by TeamCity.
This change creates a new environment variable `BUILD_NUMBER` which is `GITHUB_RUN_NUMBER` + the TeamCity offset.
The screenshot below taken from PROD, suggests we're running build 804, when in fact we are running [build 3164](https://github.com/guardian/riff-raff/actions/runs/6719327251) (804 + 2360).
When [deployed to CODE](https://riffraff.code.dev-gutools.co.uk/deployment/view/5396486b-b4ef-4044-b98c-56bd72d90845), we get the correct number:
---
Builds on https://github.com/guardian/riff-raff/pull/1229.
Inspired by …
> fix: Report build number correctly

- build.sbt
- riff-raff/app/controllers/Testing.scala
- riff-raff/app/utils/Retriable.scala
- riff-raff/conf/routes
Looks like warnings as errors was turned off in 2017 https://github.com/guardian/riff-raff/commit/38ec8bd7104740529c5238a2b5634c0defddb1a0
This reinstates that but just for match exhaustiveness warnings.
Tested and would've caught the issue in #1082 which needed to be fixed in #1262 (yep 180 PRs later).
FIXES required (before this will compile):
`[error] It would fail on the following inputs: Cons(), Empty`
`[error] It would fail on the following input: (_, _)`
> fail compile on match exhaustiveness warnings

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
Extends the changes of https://github.com/guardian/riff-raff/pull/1141, converting a warning to a failure. With this change, if an AMI cannot be found the deployment is stopped, and marked as failed.
- [Deploy to CODE](https://riffraff.code.dev-gutools.co.uk/deployment/view/0cae408b-64cb-458b-83de-127a662ad17e)
- Deploy a project that references a non-existent AMI (e.g https://github.com/guardian/cdk-playground/pull/418)
> fix: Fail a deployment if an AMI cannot be located

- project/Dependencies.scala
Bump `postgresql` to resolve a [vulnerability flagged as critical by Snyk](https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-6252740).
> chore(deps): Update postgresql to 42.7.2

- riff-raff/app/controllers/DeployController.scala
As per title. We had a team mobbing session on Riff-Raff and we decided to add this  feature to make the mapping between Riff-Raff project and Github repository clearer.
Tested locally and on CODE.
> Add Github repository name to build dropdown

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/deployment_type/GCS.scala
- magenta-lib/src/main/scala/magenta/deployment_type/GcpDeploymentManager.scala
- magenta-lib/src/main/scala/magenta/deployment_type/Param.scala
- magenta-lib/src/main/scala/magenta/deployment_type/S3ObjectPrefixParameters.scala
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/main/scala/magenta/tasks/gcp/DeploymentManagerTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- magenta-lib/src/test/scala/magenta/deployment_type/ParamTest.scala
- magenta-lib/src/test/scala/magenta/input/resolver/DeploymentTypeResolverTest.scala
This PR improves time & duration handling in Riff Raff by switching representation from `Int` or `Long` types (types which don't incorporate a time-unit, meaning we have to work out from our _context_ whether we are using seconds, milliseconds, epoch-ms, etc) to using the great `java.time.*` classes `Instant` & `Duration`.
This fixes a lot of things like:
* slightly obscure integer constants like `5 * 60 * 1000` (denoting 5 minutes)
* the inability of the compiler to check we're performing the right kind of operation to change time-units - the compiler can't know if what we're doing with an `Int` makes sense!
* variable names like `durationMillis`, where 'millis' had to be included because the declared type of `Long` isn't _telling_ us what the type is
* frequently multiplying numbers by …
> Use strongly-typed `Duration`s for time

- magenta-lib/src/main/scala/magenta/deployment_type/AutoScaling.scala
- magenta-lib/src/main/scala/magenta/tasks/ASGTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/autoscaling/CullSummary.scala
- magenta-lib/src/main/scala/magenta/tasks/tasks.scala
- magenta-lib/src/test/scala/magenta/deployment_type/AutoScalingTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTasksTest.scala
This aims to address, to an extent, issue https://github.com/guardian/riff-raff/issues/1342 - that in an  [`autoscaling`](https://riffraff.gutools.co.uk/docs/magenta-lib/types#autoscaling) deploy, **apps _can not_ auto-scale** until the original number of instances in the ASG is capable of successfully handling the level of traffic, as checked by `WaitForStabilization`. On 22nd May 2024, this inability to auto-scale led to a severe outage in the Ophan Tracker, when a large increase in pageview traffic during a deploy meant the original number of instances could never have handled the load.
Ever since https://github.com/guardian/riff-raff/pull/83 in April 2013, Riff Raff has disabled ASG scaling alarms at the start of a deploy (`SuspendAlarmNotifications`), and only re-enabled them at the …
> `autoscaling` deploy: re-enable ASG scaling before final stabilisation check

- project/Dependencies.scala
- riff-raff/app/conf/context.scala
- riff-raff/app/persistence/ContinuousDeploymentConfigRepository.scala
- riff-raff/app/persistence/DynamoRepository.scala
- riff-raff/app/persistence/HookConfigRepository.scala
- riff-raff/app/persistence/RestrictionConfigDynamoRepository.scala
- riff-raff/app/persistence/ScheduleRepository.scala
- riff-raff/app/persistence/TargetDynamoRepository.scala
Here we're moving up from Scanamo [1.0.0-M11](https://github.com/scanamo/scanamo/releases/tag/v1.0.0-M11) to [1.1.1](https://github.com/scanamo/scanamo/releases/tag/v1.1.1), which involves several changes to requirements:
* **AWS SDK v1 → v2** - Scanamo [1.0-M13](https://github.com/scanamo/scanamo/releases/tag/v1.0-M13) and above require AWS SDK v2. AWS SDK v2 is actually used quite widely already in Riff Raff, so this wasn't hard - there does still seem to be _some_ other code in Riff Raff using AWS SDK v1 at the moment.
* **Scanamo API changes**
- Auto-generated `DynamoFormat` handlers are now created with `org.scanamo.generic.auto._` rather than `org.scanamo.auto._` (https://github.com/scanamo/scanamo/pull/538 - [1.0-M12](https://github.com/scanamo/scanamo/releases/tag/v1.0.0-M12))
- …
> Upgrade to Scanamo v1.1.1

- riff-raff/app/views/deploy/viewDeploy.scala.html
Add the name of who started a deployment on log page. To make it easier to parse the amount of information, tabulate the data.
Knowing who triggered a deployment is useful in a number of scenarios. For example, when a scheduled deployment fails due to the previous deployment being a partial deployment, the team is notified thus:
The `View partial deploy` link goes to the deployment log page; knowing who did this partial deployment makes it easier to triage.
> feat: Add name of who started a deployment on log page

- riff-raff/app/AppComponents.scala
- riff-raff/app/notification/GrafanaAnnotationLogger.scala
This PR adds a new field to the grafana logger containing an html `a` tag. This is displayed by grafana as an actual link in the annotation, like in the screenshot below.
The intention is to turn the build number in our annotation to a link to the actual deployment in riff raff
We deployed this branch to riff raff code, deployed the cdk playground project, and were able to harcode grafana to display the deployment as an annotation and it seemed to work ok!
> Add link to deployment log to grafana logger

- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/SetStackPolicyTask.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
Update the `cloud-formation` deployment type to preserve any existing tags on the CloudFormation stack.
1. Deploy `main` to RIff-Raff CODE
2. Add a random tag [^1] to the stack `playground-PROD-cdk-playground` in the Developer Playground account (from https://github.com/guardian/cdk-playground)
3. Using Riff-Raff CODE, deploy the project `devx::cdk-playground`
4. Observe the tag added in step 2 being removed
5. [Deploy this branch](https://riffraff.code.dev-gutools.co.uk/deployment/view/2c220c29-9af7-4d1d-9a4b-7a8d480727dc) to Riff-Raff CODE
6. Repeat step 2
7. [Repeat step 3](https://riffraff.code.dev-gutools.co.uk/deployment/view/ae594e45-4b99-4494-b29a-42942fa0fdab)
8. Observe the tag added in step 6 remaining, and the deployment log stating as such …
> feat(cloud-formation): Preserve existing tags

- riff-raff/app/AppComponents.scala
Reverts guardian/riff-raff#1374
It's emerged that this change might break deployments for projects that use the ami update functionality. If the stack has enough components that all need to be tagged, the list of events in the cloudformation stack becomes so long that it breaks. 
See
https://github.com/guardian/riff-raff/blob/main/magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala#L34
We think that removing this tag should be safe as riff raff should not remove the tags that have already been added. It will just stop adding tags to new deployments, and the ~40 projects that rely on this ami update deployment type should continue to work without issue.
> Revert "Add riff raff project tag"

- magenta-lib/src/main/scala/magenta/deployment_type/AmiCloudFormationParameter.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormation.scala
- magenta-lib/src/main/scala/magenta/deployment_type/CloudFormationDeploymentTypeParameters.scala
- magenta-lib/src/main/scala/magenta/tasks/AWS.scala
- magenta-lib/src/main/scala/magenta/tasks/ChangeSetTasks.scala
- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
- magenta-lib/src/test/scala/magenta/deployment_type/CloudFormationTest.scala
- magenta-lib/src/test/scala/magenta/tasks/ASGTest.scala
In https://github.com/guardian/cdk/pull/2417 support was added to `@guardian/cdk` (GuCDK) to deploy application updates to an autoscaling group (ASG) via CloudFormation (CFN) with the [`AutoScalingRollingUpdate` update policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-rollingupdate).
During the [testing](https://github.com/guardian/testing-asg-rolling-update), we [observed](https://github.com/guardian/testing-asg-rolling-update/tree/main?tab=readme-ov-file#mininstancesinservice) that for a service that horizontally scales, the `MinInstanceInService` property should be set relative to the current state of the ASG. Consequently when an autoscaling group has scaling policies, GuCDK adds a parameter to the CFN …
> feat: Set `MinInstancesInService` via CFN parameters

- .github/workflows/ci.yml
- .github/workflows/sbt-dependency-graph.yaml
- .tool-versions
[From 05 December 2024](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/) the `ubuntu-latest` runner provided by GitHub will no longer contain `sbt` (https://github.com/actions/runner-images/issues/10636).
This change swaps usage of the `actions/setup-java` GitHub Action and the implicit presence of `sbt` for the [`guardian/setup-scala`](https://github.com/guardian/setup-scala) GitHub Action, which is described as:
> Combining [setup-java](https://github.com/actions/setup-java) & [setup-sbt](https://github.com/sbt/setup-sbt) with good defaults for the Guardian
A requirement of `guardian/setup-scala` is the presence of:
> an [asdf](https://asdf-vm.com/)-formatted .tool-versions file.
Thus, one is added in this PR using the latest version of Java …
> ci: Use `guardian/setup-scala` GitHub Action

- project/Dependencies.scala
Latest version should no longer rely on org.asynchttpclient:async-http-client:2.12.3, which has a critical vulnerability flagged by our dependency tree scanning.
> Update fastly-api-client to latest

- magenta-lib/src/main/scala/magenta/tasks/UpdateCloudFormationTask.scala
When using the [new deployment mechanism](https://docs.google.com/document/d/18M6nW6bknvFYjICMaSmDwkIisAuHsn4y_HSTdKu7Z-o/edit?tab=t.0) (CFN Rolling Update), CloudFormation events for the ASG are very useful.
They include details of percentage completion, success/failure reasons, etc. Surface these by default to improve the DX when using the new deployment mechanism.
I've [deployed to CODE](https://riffraff.code.dev-gutools.co.uk/deployment/view/334779e6-c454-4332-b8ea-7a1bf31f8ce9) and deployed [cdk-playground](https://riffraff.code.dev-gutools.co.uk/deployment/view/62a9c346-1812-450b-8729-8c152f712619) (uses the new deployment mechanism) and [Grafana](https://riffraff.code.dev-gutools.co.uk/deployment/view/629718e0-df02-447b-abd5-dcbe0b85be70) (uses the legacy `autoscaling` deployment). …
> feat: Display all ASG CloudFormation updates by default

- riff-raff/public/docs/howto/fix-a-failed-deploy.md
Update the "fixing a failed deploy" page with a nudge towards the new deployment mechanism.
> docs: Hint towards using the new deployment mechanism

- project/Dependencies.scala
We've received a security alert for a high severity vulnerability in the postgres library, which can be fixed by a minor version update.
> Fix high vulnerability CVE-2025-49146

- project/Dependencies.scala
Updates anghammarad-client to [6.0.0](https://github.com/guardian/anghammarad/releases/tag/v6.0.0) and the AWS SDK to [2.32.26](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.32.26). Included in this version (well [2.32.25](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.32.25)) is an update to netty 4.1.124, which should work towards resolving https://github.com/guardian/riff-raff/security/dependabot/16. We'd also need to update the following once available:
- https://github.com/scanamo/scanamo
- https://github.com/guardian/play-secret-rotation
> chore(deps): Update dependencies

- riff-raff/bootstrap.sh
- riff-raff/conf/application.conf
Prior to this change, applying a 'bad' [Play evolution](https://www.playframework.com/documentation/3.0.x/Evolutions) put the DB into an inconsistent state.
When this happens the application won't start and - as Riff-Raff runs as a singleton - we have a complete outage until we:
1. [Manually fix the DB](https://www.playframework.com/documentation/3.0.x/Evolutions#Inconsistent-states)
2. Upload the previous working build (i.e. one without the bad evolution) to S3
3. Launch a new instance to drop the 'bad' evolution
Connecting to the DB is non-trivial and we'd prefer not to do this at all (especially in `PROD`), so this PR [modifies the evolutions config so that 'bad' evolutions are automatically rolled back](https://www.playframework.com/documentation/3.0.x/Evolutions#Transactional-DDL). …
> Automatically rollback failed DB evolutions

- riff-raff/conf/evolutions/default/5.sql
This PR removes the `auth` table from the database using [Play's evolutions feature](https://www.playframework.com/documentation/3.0.x/Evolutions). This table has been unused since https://github.com/guardian/riff-raff/pull/1471 was merged.
The PR also removes a view that was made available to Service Catalogue (in https://github.com/guardian/riff-raff/pull/1273). For more context on that change, see https://github.com/guardian/service-catalogue/pull/1645.
Note that to get this to work we first need to manually run: `ALTER TABLE auth OWNER TO riffraff_app;` against the DB.
This is because these tables were created by the `riffraff` user, rather than the `riffraff_app` user that we [moved to when we started using IAM auth for RDS](https://github.com/guardian/deploy-tools-platform/pull/166). …
> Remove auth table and service catalogue view of it
